#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-06-18 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20200610_2124"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasehistory",
            name="message",
            field=models.TextField(blank=True, default="", verbose_name="发布消息"),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="stages",
            field=models.ManyToManyField(to="core.Stage"),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="status",
            field=models.CharField(
                choices=[("success", "SUCCESS"), ("failure", "FAILURE"), ("pending", "PENDING")],
                default="pending",
                max_length=16,
                verbose_name="发布状态",
            ),
        ),
        migrations.AlterField(
            model_name="releasehistory",
            name="stage",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.Stage"),
        ),
        migrations.AlterField(
            model_name="resourceversion",
            name="comment",
            field=models.CharField(blank=True, help_text="版本详细说明", max_length=512, null=True, verbose_name="版本说明"),
        ),
        migrations.AlterField(
            model_name="resourceversion",
            name="name",
            field=models.CharField(max_length=128, unique=True, verbose_name="版本号"),
        ),
        migrations.AlterField(
            model_name="resourceversion",
            name="title",
            field=models.CharField(
                blank=True, default="", help_text="版本名称，概述", max_length=128, null=True, verbose_name="版本名称"
            ),
        ),
    ]
