# Generated by Django 3.2.18 on 2023-07-04 09:13

from django.db import migrations, models

import apigateway.core.constants


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230227_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishEvent',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_id', models.IntegerField(db_index=True)),
                ('stage_id', models.IntegerField(db_index=True)),
                ('release_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('step', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('failure', 'FAILURE'), ('pending', 'PENDING'), ('releasing', 'RELEASING')], default='pending', max_length=16, verbose_name='publish event status')),
                ('detail', models.TextField(blank=True, default='', help_text='event detail')),
            ],
            options={
                'verbose_name': 'PublishEvent',
                'verbose_name_plural': 'PublishEvent',
                'db_table': 'core_publish_event',
            },
        ),
        migrations.AddField(
            model_name='releasehistory',
            name='operation',
            field=models.CharField(blank=True, choices=[('add', 'ADD'), ('update', 'UPDATE'), ('delete', 'DELETE'), ('publish', 'PUBLISH'), ('enable', 'ENABLE'), ('disable', 'DISABLE')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='releasehistory',
            name='situation',
            field=models.CharField(blank=True, choices=[('plugin', 'PLUGIN'), ('stage', 'STAGE'), ('version', 'VERSION')], default=apigateway.core.constants.ReleaseSituationEnum['VERSION'], max_length=64, null=True),
        ),
    ]
