# Generated by Django 3.2.18 on 2023-07-07 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230227_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishEvent',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[('generate_release_task', 'generate release task')], max_length=64)),
                ('step', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'success'), ('failure', 'failure'), ('pending', 'pending'), ('doing', 'doing')], max_length=32)),
                ('_detail', models.TextField(db_column='detail', default='{}', help_text='detail', null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.gateway')),
                ('publish', models.ForeignKey(db_column='publish_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.releasehistory')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.stage')),
            ],
            options={
                'verbose_name': 'PublishEvent',
                'verbose_name_plural': 'PublishEvent',
                'db_table': 'core_publish_event',
                'index_together': {('gateway_id', 'publish_id')},
            },
        ),
    ]
