#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 3.2.18 on 2023-07-07 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230227_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishEvent',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[('generate_release_task', 'generate release task')], max_length=64)),
                ('step', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'success'), ('failure', 'failure'), ('pending', 'pending'), ('doing', 'doing')], max_length=32)),
                ('_detail', models.TextField(db_column='detail', default='{}', help_text='detail', null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.gateway')),
                ('publish', models.ForeignKey(db_column='publish_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.releasehistory')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.stage')),
            ],
            options={
                'verbose_name': 'PublishEvent',
                'verbose_name_plural': 'PublishEvent',
                'db_table': 'core_publish_event',
                'index_together': {('gateway_id', 'publish_id')},
            },
        ),
    ]
