# Generated by Django 3.2.18 on 2023-08-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_publishevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishevent',
            name='name',
            field=models.CharField(blank=True, choices=[('generate_release_task', 'generate release task'), ('distribute_configuration', 'distribute configuration'), ('parse_configuration', 'parse configuration'), ('apply_configuration', 'apply configuration'), ('load_configuration', 'load configuration')], max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='publishevent',
            unique_together={('gateway_id', 'publish_id', 'step', 'status')},
        ),
    ]
