# Generated by Django 3.2.18 on 2023-08-04 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230802_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publishevent',
            unique_together={('gateway_id', 'publish_id', 'stage_id', 'step', 'status')},
        ),
    ]
