# Generated by Django 3.2.18 on 2023-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_publishevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='_developers',
            field=models.CharField(blank=True, db_column='developers', default='', max_length=1024, null=True),
        ),
    ]
