# Generated by Django 3.2.18 on 2023-08-10 06:58

import apigateway.core.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_publishevent_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasehistory',
            old_name='api',
            new_name='gateway',
        ),
        migrations.AddField(
            model_name='releasehistory',
            name='source',
            field=models.CharField(choices=[('gateway_enable', '网关启用'), ('gateway_disable', '网关停用'), ('resource_publish', '资源发布'), ('plugin_update', '插件更新'), ('stage_disable', '环境下架'), ('stage_env_update', '变量更新'), ('backend_update', '服务更新')], default=apigateway.core.constants.PublishSourceEnum['RESOURCE_PUBLISH'], max_length=64),
        ),
        migrations.AlterField(
            model_name='releasehistory',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
    ]
