#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the 'License'); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 3.2.18 on 2023-08-14 11:20

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_gateway__developers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                (
                    'type',
                    models.CharField(choices=[('HTTP', 'HTTP'), ('GRPC', 'GRPC')], default='HTTP', max_length=20),
                ),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gateway')),
            ],
            options={
                'db_table': 'core_backend',
                'unique_together': {('gateway', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BackendConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('config', jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'indent': None})),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.backend')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gateway')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stage')),
            ],
            options={
                'db_table': 'core_backend_config',
                'unique_together': {('gateway', 'backend', 'stage')},
            },
        ),
    ]
