# Generated by Django 3.2.18 on 2023-08-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_backend_backendconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='api',
            new_name='gateway',
        ),
        migrations.AlterField(
            model_name='backend',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='backend',
            name='type',
            field=models.CharField(choices=[('http', 'HTTP'), ('grpc', 'GRPC')], default='http', max_length=20),
        ),
        migrations.AlterField(
            model_name='stage',
            name='_vars',
            field=models.TextField(db_column='vars', default='{}'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.PROTECT, to='core.gateway'),
        ),
        migrations.AlterField(
            model_name='stageitem',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('gateway', 'name')},
        ),
    ]
