# Generated by Django 3.2.18 on 2023-08-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20230824_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceversion',
            name='scheme_version',
            field=models.CharField(choices=[('1.0', '旧模型版本'), ('2.0', '新模型版本')], default='1.0', max_length=32),
        )
    ]
