# Generated by Django 3.2.18 on 2023-08-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20230824_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='backend',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.backend'),
        ),
    ]
