#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 3.2.18 on 2023-09-02 05:07

from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_proxy_backend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirelatedapp',
            old_name='api',
            new_name='gateway',
        ),
        migrations.RenameField(
            model_name='jwt',
            old_name='api',
            new_name='gateway',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='api',
            new_name='gateway',
        ),
        migrations.RenameField(
            model_name='sslcertificate',
            old_name='api',
            new_name='gateway',
        ),
        migrations.RenameField(
            model_name='sslcertificatebinding',
            old_name='api',
            new_name='gateway',
        ),
        migrations.AddField(
            model_name='resourceversion',
            name='schema_version',
            field=models.CharField(choices=[('1.0', '旧模型版本'), ('2.0', '新模型版本')], default='1.0', max_length=32),
        ),

        AddDefaultValue(
            model_name='resourceversion',
            name='schema_version',
            value='1.0'
        ),

        migrations.AlterField(
            model_name='apirelatedapp',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
        migrations.AlterField(
            model_name='jwt',
            name='gateway',
            field=models.OneToOneField(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.gateway'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.PROTECT, to='core.gateway'),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
        migrations.AlterField(
            model_name='sslcertificatebinding',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
        migrations.AlterUniqueTogether(
            name='sslcertificatebinding',
            unique_together={('gateway', 'scope_type', 'scope_id', 'ssl_certificate')},
        ),
    ]
