# Generated by Django 3.2.18 on 2024-02-22 04:08

from django.core.management import call_command
from django.db import migrations


def run_migrate_command(apps, schema_editor):
    call_command("migrate_access_strategy")
    call_command("migrate_backend")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20231023_1526'),
    ]

    operations = [migrations.RunPython(run_migrate_command)]
