# Generated by Django 3.2.25 on 2024-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_update_1_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='backend_config_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
