# Generated by Django 3.2.25 on 2024-04-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_update_1_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishevent',
            name='name',
            field=models.CharField(blank=True, choices=[('validata_configuration', '配置校验'), ('generate_release_task', '生成发布任务'), ('distribute_configuration', '下发配置'), ('parse_configuration', '解析配置'), ('apply_configuration', '应用配置'), ('load_configuration', '加载配置')], max_length=64),
        ),
    ]
