# Generated by Django 3.2.25 on 2024-08-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20240517_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='enable_websocket',
            field=models.BooleanField(default=False),
        ),
    ]
