# Generated by Django 4.2.20 on 2025-04-03 09:32

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_auto_20240826_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="_doc_maintainers",
            field=jsonfield.fields.JSONField(
                blank=True, db_column="doc_maintainers", default=dict, dump_kwargs={"indent": None}, null=True
            ),
        ),
    ]
