# Generated by Django 3.2.25 on 2024-07-19 10:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20240718_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedebughistory',
            name='request_params',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'indent': None}),
        ),
    ]
