# Generated by Django 4.2.20 on 2025-03-31 09:17

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20240826_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='doc_maintainers',
            field=jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'indent': None}),
        ),
    ]
