# Generated by Django 3.2.25 on 2024-07-19 11:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_resourcedebughistory_request_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedebughistory',
            name='request_params',
            field=jsonfield.fields.JSONField(blank=True, help_text='请求参数'),
        ),
    ]
