# Generated by Django 4.2.16 on 2024-12-07 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_add_gateway_tenant"),
    ]

    operations = [
        # remove fieleds already not in code definition
        migrations.RemoveField(
            model_name="proxy",
            name="backend_config_type",
        ),
        migrations.RemoveField(
            model_name="proxy",
            name="backend_service",
        ),
        # remove fields of models already not in code definition
        migrations.RemoveField(
            model_name="sslcertificate",
            name="gateway",
        ),
        migrations.AlterUniqueTogether(
            name="sslcertificatebinding",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sslcertificatebinding",
            name="gateway",
        ),
        migrations.RemoveField(
            model_name="sslcertificatebinding",
            name="ssl_certificate",
        ),
        migrations.RemoveField(
            model_name="stageitem",
            name="api",
        ),
        migrations.AlterUniqueTogether(
            name="stageitemconfig",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="stageitemconfig",
            name="api",
        ),
        migrations.RemoveField(
            model_name="stageitemconfig",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="stageitemconfig",
            name="stage_item",
        ),
        # remove table already not in code definition
        migrations.DeleteModel(
            name="BackendService",
        ),
        migrations.DeleteModel(
            name="SslCertificate",
        ),
        migrations.DeleteModel(
            name="SslCertificateBinding",
        ),
        migrations.DeleteModel(
            name="StageItem",
        ),
        migrations.DeleteModel(
            name="StageItemConfig",
        ),
        # alter fields, with default value and allow null
        # those fields would be remove from code definition in the next version, then remove the field from db in the future
        migrations.AlterField(
            model_name="gateway",
            name="hosting_type",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="schema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="schema.schema",
            ),
        ),
        migrations.AlterField(
            model_name="resourceversion",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                null=True,
                verbose_name="[Deprecated] 版本名",
            ),
        ),
        migrations.AlterField(
            model_name="releasehistory",
            name="message",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="releasehistory",
            name="stages",
            field=models.ManyToManyField(blank=True, to="core.stage"),
        ),
        migrations.AlterField(
            model_name="releasehistory",
            name="status",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                null=True,
                verbose_name="发布状态",
            ),
        ),
    ]
