# Generated by Django 4.2.20 on 2025-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_microgatewayreleasehistory_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(0, '普通网关'), (1, '可编程网关')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='_extra_info',
            field=models.JSONField(blank=True, db_column='extra_info', default={}, null=True),
        ),
    ]
