# Generated by Django 4.2.20 on 2025-05-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_remove_sslcertificate_gateway_and_more"),
        ("core", "0044_gateway_kind"),
    ]

    operations = []
