# Generated by Django 4.2.23 on 2025-12-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20250530_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='deprecated_note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
