# Generated by Django 4.2.23 on 2025-10-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20250530_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='micro_gateway',
        ),
    ]
