# Generated by Django 4.2.23 on 2025-12-15 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_gateway_deprecated_note_gateway_is_deprecated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="micro_gateway",
        ),
        migrations.DeleteModel(
            name="MicroGateway",
        ),
    ]
