# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_remove_micro_gateway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.CharField(blank=True, default="", max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description_en",
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
