# Generated by Django 4.2.20 on 2025-01-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_plane", "0001_initial"),
        ("core", "0048_alter_resource_description_max_length_to_2048"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasehistory",
            name="data_plane",
            field=models.ForeignKey(
                blank=True,
                help_text="The data plane this release was published to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="release_histories",
                to="data_plane.dataplane",
            ),
        ),
    ]
