# Generated by Django 4.2.30 on 2026-06-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_releasehistory_data_plane"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="publishevent",
            index=models.Index(fields=["created_time"], name="core_pub_evt_ct_idx"),
        ),
    ]
