# Generated by Django 5.2.15 on 2026-07-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_gateway_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='kind',
            field=models.CharField(choices=[('standard', '普通后端服务'), ('ai', '模型服务')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('standard', '普通 API'), ('ai', '模型代理 API')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(0, '普通网关'), (1, '可编程网关'), (2, 'AI 网关')], default=0, null=True),
        ),
    ]
