# Generated by Django 5.2.15 on 2026-07-14

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_add_ai_gateway_model_kinds"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name="backendconfig",
                    old_name="config",
                    new_name="_config",
                ),
                migrations.AlterField(
                    model_name="backendconfig",
                    name="_config",
                    field=jsonfield.fields.JSONField(
                        blank=True,
                        db_column="config",
                        default=dict,
                        dump_kwargs={"indent": None},
                    ),
                ),
            ],
        ),
    ]
