# Generated by Django 5.2.15 on 2026-07-29

from django.db import migrations, models
from django.db.migrations.recorder import MigrationRecorder

RELEASE_BACKPORT_MIGRATION = ("core", "0053_resource_oauth2_client_fields")


def _column_names(schema_editor, model):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                model._meta.db_table,
            )
        }


def _make_boolean_field(model, field_name):
    field = models.BooleanField(default=False)
    field.set_attributes_from_name(field_name)
    field.model = model
    return field


def _add_field_if_missing(apps, schema_editor, field_name):
    Resource = apps.get_model("core", "Resource")
    if field_name not in _column_names(schema_editor, Resource):
        schema_editor.add_field(Resource, _make_boolean_field(Resource, field_name))


def _remove_field_if_owned(apps, schema_editor, field_name):
    applied_migrations = MigrationRecorder(schema_editor.connection).applied_migrations()
    if RELEASE_BACKPORT_MIGRATION in applied_migrations:
        return

    Resource = apps.get_model("core", "Resource")
    if field_name in _column_names(schema_editor, Resource):
        schema_editor.remove_field(Resource, _make_boolean_field(Resource, field_name))


def add_oauth2_personal_client_enabled(apps, schema_editor):
    _add_field_if_missing(apps, schema_editor, "oauth2_personal_client_enabled")


def remove_oauth2_personal_client_enabled(apps, schema_editor):
    _remove_field_if_owned(apps, schema_editor, "oauth2_personal_client_enabled")


def add_oauth2_public_client_enabled(apps, schema_editor):
    _add_field_if_missing(apps, schema_editor, "oauth2_public_client_enabled")


def remove_oauth2_public_client_enabled(apps, schema_editor):
    _remove_field_if_owned(apps, schema_editor, "oauth2_public_client_enabled")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_backendconfig_private_config"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_oauth2_personal_client_enabled,
                    remove_oauth2_personal_client_enabled,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="resource",
                    name="oauth2_personal_client_enabled",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_oauth2_public_client_enabled,
                    remove_oauth2_public_client_enabled,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="resource",
                    name="oauth2_public_client_enabled",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
