# Generated by Django 5.2.15 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_backendconfig_private_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="oauth2_personal_client_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="oauth2_public_client_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
