# Generated by Django 5.2.15 on 2026-08-03

import json

from django.db import migrations, models
from django.db.migrations.recorder import MigrationRecorder

BATCH_SIZE = 1000
RELEASE_BACKPORT_MIGRATION = ("core", "0054_releasedresource_oauth2_scope_fields")


def _column_names(schema_editor, model):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                model._meta.db_table,
            )
        }


def _constraint_names(schema_editor, model):
    with schema_editor.connection.cursor() as cursor:
        return set(
            schema_editor.connection.introspection.get_constraints(
                cursor,
                model._meta.db_table,
            )
        )


def _release_backport_was_applied(schema_editor):
    return RELEASE_BACKPORT_MIGRATION in MigrationRecorder(schema_editor.connection).applied_migrations()


def _make_boolean_field(model, field_name):
    field = models.BooleanField(default=False)
    field.set_attributes_from_name(field_name)
    field.model = model
    return field


def _add_field_if_missing(apps, schema_editor, field_name):
    ReleasedResource = apps.get_model("core", "ReleasedResource")
    if field_name not in _column_names(schema_editor, ReleasedResource):
        schema_editor.add_field(ReleasedResource, _make_boolean_field(ReleasedResource, field_name))


def _remove_field_if_owned(apps, schema_editor, field_name):
    if _release_backport_was_applied(schema_editor):
        return

    ReleasedResource = apps.get_model("core", "ReleasedResource")
    if field_name in _column_names(schema_editor, ReleasedResource):
        schema_editor.remove_field(ReleasedResource, _make_boolean_field(ReleasedResource, field_name))


def add_is_public(apps, schema_editor):
    _add_field_if_missing(apps, schema_editor, "is_public")


def remove_is_public(apps, schema_editor):
    _remove_field_if_owned(apps, schema_editor, "is_public")


def add_oauth2_public_client_enabled(apps, schema_editor):
    _add_field_if_missing(apps, schema_editor, "oauth2_public_client_enabled")


def remove_oauth2_public_client_enabled(apps, schema_editor):
    _remove_field_if_owned(apps, schema_editor, "oauth2_public_client_enabled")


def add_oauth2_personal_client_enabled(apps, schema_editor):
    _add_field_if_missing(apps, schema_editor, "oauth2_personal_client_enabled")


def remove_oauth2_personal_client_enabled(apps, schema_editor):
    _remove_field_if_owned(apps, schema_editor, "oauth2_personal_client_enabled")


def _make_index(name):
    client_flag = {
        "rr_oauth_pub_scope_idx": "oauth2_public_client_enabled",
        "rr_oauth_personal_scope_idx": "oauth2_personal_client_enabled",
    }[name]
    return models.Index(
        fields=[client_flag, "is_public", "gateway", "resource_version_id", "resource_id"],
        name=name,
    )


def _add_index_if_missing(apps, schema_editor, name):
    ReleasedResource = apps.get_model("core", "ReleasedResource")
    if name not in _constraint_names(schema_editor, ReleasedResource):
        schema_editor.add_index(ReleasedResource, _make_index(name))


def _remove_index_if_owned(apps, schema_editor, name):
    if _release_backport_was_applied(schema_editor):
        return

    ReleasedResource = apps.get_model("core", "ReleasedResource")
    if name in _constraint_names(schema_editor, ReleasedResource):
        schema_editor.remove_index(ReleasedResource, _make_index(name))


def add_public_scope_index(apps, schema_editor):
    _add_index_if_missing(apps, schema_editor, "rr_oauth_pub_scope_idx")


def remove_public_scope_index(apps, schema_editor):
    _remove_index_if_owned(apps, schema_editor, "rr_oauth_pub_scope_idx")


def add_personal_scope_index(apps, schema_editor):
    _add_index_if_missing(apps, schema_editor, "rr_oauth_personal_scope_idx")


def remove_personal_scope_index(apps, schema_editor):
    _remove_index_if_owned(apps, schema_editor, "rr_oauth_personal_scope_idx")


def _get_flags(data):
    try:
        raw_config = data["contexts"]["resource_auth"]["config"]
        config = json.loads(raw_config) if isinstance(raw_config, str) else raw_config
    except (KeyError, TypeError, ValueError):
        return False, False

    if not isinstance(config, dict):
        return False, False

    return (
        config.get("oauth2_public_client_enabled") is True,
        config.get("oauth2_personal_client_enabled") is True,
    )


def backfill_released_resource_scope_fields(apps, schema_editor):
    if _release_backport_was_applied(schema_editor):
        return

    ReleasedResource = apps.get_model("core", "ReleasedResource")
    pending = []
    queryset = ReleasedResource.objects.only("id", "data").order_by("id")

    for released in queryset.iterator(chunk_size=BATCH_SIZE):
        data = released.data if isinstance(released.data, dict) else {}
        public_enabled, personal_enabled = _get_flags(data)
        released.is_public = data.get("is_public") is True
        released.oauth2_public_client_enabled = public_enabled
        released.oauth2_personal_client_enabled = personal_enabled
        pending.append(released)

        if len(pending) == BATCH_SIZE:
            ReleasedResource.objects.bulk_update(
                pending,
                ["is_public", "oauth2_public_client_enabled", "oauth2_personal_client_enabled"],
                batch_size=BATCH_SIZE,
            )
            pending.clear()

    if pending:
        ReleasedResource.objects.bulk_update(
            pending,
            ["is_public", "oauth2_public_client_enabled", "oauth2_personal_client_enabled"],
            batch_size=BATCH_SIZE,
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0055_resource_oauth2_client_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_is_public, remove_is_public)],
            state_operations=[
                migrations.AddField(
                    model_name="releasedresource",
                    name="is_public",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_oauth2_public_client_enabled, remove_oauth2_public_client_enabled)
            ],
            state_operations=[
                migrations.AddField(
                    model_name="releasedresource",
                    name="oauth2_public_client_enabled",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_oauth2_personal_client_enabled, remove_oauth2_personal_client_enabled)
            ],
            state_operations=[
                migrations.AddField(
                    model_name="releasedresource",
                    name="oauth2_personal_client_enabled",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.RunPython(
            backfill_released_resource_scope_fields,
            migrations.RunPython.noop,
            atomic=False,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_public_scope_index, remove_public_scope_index)],
            state_operations=[
                migrations.AddIndex(
                    model_name="releasedresource",
                    index=_make_index("rr_oauth_pub_scope_idx"),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_personal_scope_index, remove_personal_scope_index)],
            state_operations=[
                migrations.AddIndex(
                    model_name="releasedresource",
                    index=_make_index("rr_oauth_personal_scope_idx"),
                ),
            ],
        ),
    ]
