# Generated by Django 5.2.15 on 2026-08-03

import json

from django.db import migrations, models

BATCH_SIZE = 1000


def _get_flags(data):
    try:
        raw_config = data["contexts"]["resource_auth"]["config"]
        config = json.loads(raw_config) if isinstance(raw_config, str) else raw_config
    except (KeyError, TypeError, ValueError):
        return False, False

    if not isinstance(config, dict):
        return False, False

    return (
        config.get("oauth2_public_client_enabled") is True,
        config.get("oauth2_personal_client_enabled") is True,
    )


def backfill_released_resource_scope_fields(apps, schema_editor):
    ReleasedResource = apps.get_model("core", "ReleasedResource")
    pending = []
    queryset = ReleasedResource.objects.only("id", "data").order_by("id")

    for released in queryset.iterator(chunk_size=BATCH_SIZE):
        data = released.data if isinstance(released.data, dict) else {}
        public_enabled, personal_enabled = _get_flags(data)
        released.is_public = data.get("is_public") is True
        released.oauth2_public_client_enabled = public_enabled
        released.oauth2_personal_client_enabled = personal_enabled
        pending.append(released)

        if len(pending) == BATCH_SIZE:
            ReleasedResource.objects.bulk_update(
                pending,
                ["is_public", "oauth2_public_client_enabled", "oauth2_personal_client_enabled"],
                batch_size=BATCH_SIZE,
            )
            pending.clear()

    if pending:
        ReleasedResource.objects.bulk_update(
            pending,
            ["is_public", "oauth2_public_client_enabled", "oauth2_personal_client_enabled"],
            batch_size=BATCH_SIZE,
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0055_resource_oauth2_client_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasedresource",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="releasedresource",
            name="oauth2_public_client_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="releasedresource",
            name="oauth2_personal_client_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            backfill_released_resource_scope_fields,
            migrations.RunPython.noop,
            atomic=False,
        ),
        migrations.AddIndex(
            model_name="releasedresource",
            index=models.Index(
                fields=[
                    "oauth2_public_client_enabled",
                    "is_public",
                    "gateway",
                    "resource_version_id",
                    "resource_id",
                ],
                name="rr_oauth_pub_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="releasedresource",
            index=models.Index(
                fields=[
                    "oauth2_personal_client_enabled",
                    "is_public",
                    "gateway",
                    "resource_version_id",
                    "resource_id",
                ],
                name="rr_oauth_personal_scope_idx",
            ),
        ),
    ]
