#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2019-11-27 02:24

import django.db.models.deletion
from django.db import migrations, models

import apigateway.apps.permission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppAPIPermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("bk_app_code", models.CharField(db_index=True, max_length=32)),
                (
                    "expires",
                    models.DateTimeField(
                        blank=True,
                        default=apigateway.apps.permission.models.generate_expire_time,
                        help_text="默认过期时间为180天",
                        null=True,
                    ),
                ),
                ("api", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.API")),
            ],
            options={
                "verbose_name": "蓝鲸应用访问网关权限",
                "verbose_name_plural": "蓝鲸应用访问网关权限",
                "db_table": "permission_app_api",
            },
        ),
        migrations.CreateModel(
            name="AppPermissionApply",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("bk_app_code", models.CharField(db_index=True, max_length=32)),
                ("applied_by", models.CharField(max_length=32)),
                ("_resource_ids", models.TextField(db_column="resource_ids")),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "已同意"), ("rejected", "已驳回"), ("pending", "待审批")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("api", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.API")),
            ],
            options={
                "verbose_name": "蓝鲸应用访问资源权限申请单",
                "verbose_name_plural": "蓝鲸应用访问资源权限申请单",
                "db_table": "permission_app_apply",
            },
        ),
        migrations.CreateModel(
            name="AppPermissionApplyStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("bk_app_code", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "已同意"), ("rejected", "已驳回"), ("pending", "待审批")], max_length=16
                    ),
                ),
                (
                    "apply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permission.AppPermissionApply",
                    ),
                ),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Resource")),
            ],
            options={
                "verbose_name": "蓝鲸应用访问资源权限申请状态",
                "verbose_name_plural": "蓝鲸应用访问资源权限申请状态",
                "db_table": "permission_app_apply_status",
            },
        ),
        migrations.CreateModel(
            name="AppPermissionRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_app_code", models.CharField(db_index=True, max_length=32)),
                ("applied_by", models.CharField(max_length=32)),
                ("applied_time", models.DateTimeField()),
                ("handled_by", models.CharField(blank=True, default="", max_length=32)),
                ("handled_time", models.DateTimeField(blank=True, null=True)),
                ("_resource_ids", models.TextField(db_column="resource_ids")),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "已同意"), ("rejected", "已驳回"), ("pending", "待审批")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=512)),
                ("api", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.API")),
            ],
            options={
                "verbose_name": "蓝鲸应用访问资源权限已审批单据",
                "verbose_name_plural": "蓝鲸应用访问资源权限已审批单据",
                "db_table": "permission_app_record",
            },
        ),
        migrations.CreateModel(
            name="AppResourcePermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("bk_app_code", models.CharField(db_index=True, max_length=32)),
                (
                    "expires",
                    models.DateTimeField(
                        blank=True,
                        default=apigateway.apps.permission.models.generate_expire_time,
                        help_text="默认过期时间为180天",
                        null=True,
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[("initialize", "INITIALIZE"), ("apply", "APPLY")], db_index=True, max_length=16
                    ),
                ),
                ("api", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.API")),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Resource")),
            ],
            options={
                "verbose_name": "蓝鲸应用访问资源权限",
                "verbose_name_plural": "蓝鲸应用访问资源权限",
                "db_table": "permission_app_resource",
            },
        ),
        migrations.AlterUniqueTogether(
            name="appresourcepermission",
            unique_together={("bk_app_code", "api", "resource")},
        ),
        migrations.AlterUniqueTogether(
            name="apppermissionapplystatus",
            unique_together={("bk_app_code", "resource")},
        ),
        migrations.AlterUniqueTogether(
            name="appapipermission",
            unique_together={("bk_app_code", "api")},
        ),
    ]
