#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-01-14 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20201021_1734"),
        ("permission", "0005_auto_20200619_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppermissionapply",
            name="grant_dimension",
            field=models.CharField(
                choices=[("api", "API"), ("resource", "RESOURCE")], db_index=True, default="resource", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="apppermissionapplystatus",
            name="api",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.API"),
        ),
        migrations.AddField(
            model_name="apppermissionapplystatus",
            name="grant_dimension",
            field=models.CharField(
                choices=[("api", "API"), ("resource", "RESOURCE")], db_index=True, default="resource", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="apppermissionrecord",
            name="grant_dimension",
            field=models.CharField(
                choices=[("api", "API"), ("resource", "RESOURCE")], db_index=True, default="resource", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="apppermissionapplystatus",
            name="resource",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.Resource"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apppermissionapplystatus",
            unique_together={("bk_app_code", "api", "resource")},
        ),
    ]
