#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-02-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0007_auto_20210115_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppermissionapply",
            name="apply_record_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apppermissionapply",
            name="grant_dimension",
            field=models.CharField(
                choices=[
                    ("api", "按网关"),
                    ("resource", "按资源"),
                ],
                db_index=True,
                default="resource",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="apppermissionapply",
            name="status",
            field=models.CharField(
                choices=[
                    ("partial_approved", "部分通过"),
                    ("approved", "全部通过"),
                    ("rejected", "全部驳回"),
                    ("pending", "待审批"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="apppermissionapplystatus",
            name="grant_dimension",
            field=models.CharField(
                choices=[
                    ("api", "按网关"),
                    ("resource", "按资源"),
                ],
                db_index=True,
                default="resource",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="apppermissionapplystatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("partial_approved", "部分通过"),
                    ("approved", "全部通过"),
                    ("rejected", "全部驳回"),
                    ("pending", "待审批"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="apppermissionrecord",
            name="_handled_resource_ids",
            field=models.TextField(blank=True, db_column="handled_resource_ids", default="{}"),
        ),
        migrations.AlterField(
            model_name="apppermissionrecord",
            name="_resource_ids",
            field=models.TextField(blank=True, db_column="resource_ids", default=""),
        ),
        migrations.AlterField(
            model_name="apppermissionrecord",
            name="grant_dimension",
            field=models.CharField(
                choices=[
                    ("api", "按网关"),
                    ("resource", "按资源"),
                ],
                db_index=True,
                default="resource",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="apppermissionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("partial_approved", "部分通过"),
                    ("approved", "全部通过"),
                    ("rejected", "全部驳回"),
                    ("pending", "待审批"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
