#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-02-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0008_auto_20210203_1544"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apppermissionapply",
            options={"verbose_name": "蓝鲸应用访问资源权限待审批申请单", "verbose_name_plural": "蓝鲸应用访问资源权限待审批申请单"},
        ),
        migrations.AlterModelOptions(
            name="apppermissionrecord",
            options={"verbose_name": "蓝鲸应用访问资源权限申请单", "verbose_name_plural": "蓝鲸应用访问资源权限申请单"},
        ),
    ]
