# Generated by Django 3.2.25 on 2024-04-19 02:55

from django.core.management import call_command
from django.db import migrations


def run_migrate_command(apps, schema_editor):
    call_command("migrate_iam_manager")


class Migration(migrations.Migration):

    dependencies = [
        ('apigw_iam_migration', '0004_common_actions'),
    ]

    operations = [migrations.RunPython(run_migrate_command)]
