run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # include test files or not, default is true
  tests: false
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  issues.exclude-files:
    - ".*/mock/.*.go"
    - ".*testing.go"

linters:
  # enable-all: true
  # disable-all: true
  disable:
    - errcheck
  enable:
    - nilerr
    - nakedret
    - lll
    - gofmt
    - gocritic
    - gocyclo
    - whitespace
    - stylecheck
    - misspell
    - goimports
    # - bodyclose
    # - nestif
    # - gofumpt
    # - godox
    # - wsl
    # - funlen
    # - golint
    # - cyclop
  fast: false

linters-settings:
  stylecheck:
    checks: ["-ST1000", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  goimports:
      # A comma-separated list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: ""
      local-prefixes: "core"
