#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2019-11-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("context", "CONTEXT"),
                            ("proxy", "PROXY"),
                            ("access_strategy", "ACCESS_STRATEGY"),
                            ("monitor", "MONITOR"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("_schema", models.TextField(db_column="schema")),
                ("description", models.CharField(max_length=512)),
                ("example", models.TextField()),
            ],
            options={
                "verbose_name": "Schema",
                "verbose_name_plural": "Schemas",
                "db_table": "schema",
            },
        ),
        migrations.AlterUniqueTogether(
            name="schema",
            unique_together={("name", "type", "version")},
        ),
    ]
