# Generated by Django 3.2.18 on 2023-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_auto_20220307_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.CharField(choices=[('context', 'CONTEXT'), ('proxy', 'PROXY'), ('plugin', 'PLUGIN'), ('monitor', 'MONITOR'), ('apisdk', 'APISDK'), ('micro_gateway', 'MICRO_GATEWAY'), ('backend_service', 'BACKEND_SERVICE')], max_length=32),
        ),
    ]
