version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: false
linters:
  enable:
    - gocritic
    - gocyclo
    - lll
    - misspell
    - nakedret
    - nilerr
    - staticcheck
    - whitespace
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - -ST1000
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: false
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    goimports:
      local-prefixes:
        - mcp_proxy
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$


