# Generated by Django 4.2.20 on 2025-01-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0044_gateway_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPlane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Data plane name",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Data plane description",
                        max_length=512,
                    ),
                ),
                (
                    "_encrypted_etcd_configs",
                    models.TextField(
                        blank=True,
                        db_column="encrypted_etcd_configs",
                        default="",
                        help_text="Encrypted ETCD configuration in JSON format",
                    ),
                ),
                (
                    "bk_api_url_tmpl",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API URL template",
                        max_length=512,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "active"), (0, "inactive")],
                        default=1,
                        help_text="Data plane status",
                    ),
                ),
                (
                    "is_recommend",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the recommended data plane",
                    ),
                ),
            ],
            options={
                "verbose_name": "DataPlane",
                "verbose_name_plural": "DataPlane",
                "db_table": "data_plane",
            },
        ),
        migrations.CreateModel(
            name="GatewayDataPlaneBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "data_plane",
                    models.ForeignKey(
                        help_text="The data plane",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_bindings",
                        to="data_plane.dataplane",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        help_text="The gateway",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_plane_bindings",
                        to="core.gateway",
                    ),
                ),
            ],
            options={
                "verbose_name": "GatewayDataPlaneBinding",
                "verbose_name_plural": "GatewayDataPlaneBinding",
                "db_table": "gateway_data_plane_binding",
                "unique_together": {("gateway", "data_plane")},
            },
        ),
    ]
