# Generated by Django 5.2.15 on 2026-08-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_plane", "0002_dataplane_apisix_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataplane",
            name="apisix_version",
            field=models.CharField(
                choices=[("3.13", "3.13"), ("3.16", "3.16"), ("3.18", "3.18")],
                default="3.18",
                help_text="APISIX version of the data plane",
                max_length=16,
            ),
        ),
    ]
