#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_auto_20200623_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmstrategy",
            name="alarm_subtype",
            field=models.CharField(
                choices=[
                    ("status_code_5xx", "后端响应状态码5xx"),
                    ("gateway_timeout", "请求后端响应超时"),
                    ("status_code_5xx", "请求后端502错误"),
                ],
                db_index=True,
                default="",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="alarmfilterconfig",
            name="alarm_type",
            field=models.CharField(
                choices=[("resource_backend", "请求资源后端错误"), ("app_request", "蓝鲸应用请求错误"), ("nginx_error", "Nginx错误")],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="alarmstrategy",
            name="alarm_type",
            field=models.CharField(choices=[("resource_backend", "请求资源后端错误")], db_index=True, max_length=64),
        ),
    ]
