# Generated by Django 4.2.16 on 2025-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0009_auto_20230902_1307"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarmstrategy",
            name="_api_label_ids",
        ),
        migrations.AddField(
            model_name="alarmstrategy",
            name="_effective_stages",
            field=models.TextField(
                blank=True, db_column="effective_stages", default=""
            ),
        ),
    ]
