# Generated by Django 5.2.15 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0010_remove_alarmstrategy__api_label_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmrecord",
            name="app_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="alarm_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resource_backend", "请求资源后端错误"),
                    ("app_request", "蓝鲸应用请求错误"),
                    ("nginx_error", "Nginx错误"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["app_code", "alarm_type", "id"],
                name="monitor_ar_app_type_id_idx",
            ),
        ),
    ]
