# Generated by Django 5.2.15 on 2026-07-03

import json

from django.db import migrations, models


def fill_alarm_record_resource_id(apps, schema_editor):
    AlarmRecord = apps.get_model("monitor", "AlarmRecord")

    records_to_update = []
    queryset = (
        AlarmRecord.objects.filter(resource_id__isnull=True)
        .exclude(match_dimension="")
        .only("id", "match_dimension", "resource_id")
        .order_by("id")
    )

    for record in queryset.iterator(chunk_size=1000):
        try:
            match_dimension = json.loads(record.match_dimension)
        except (TypeError, ValueError):
            continue

        if not isinstance(match_dimension, dict):
            continue

        resource_id = match_dimension.get("resource_id")
        if isinstance(resource_id, str) and resource_id.isdigit():
            resource_id = int(resource_id)

        if not isinstance(resource_id, int):
            continue

        record.resource_id = resource_id
        records_to_update.append(record)
        if len(records_to_update) >= 1000:
            AlarmRecord.objects.bulk_update(records_to_update, ["resource_id"])
            records_to_update = []

    if records_to_update:
        AlarmRecord.objects.bulk_update(records_to_update, ["resource_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0010_remove_alarmstrategy__api_label_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmrecord",
            name="app_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="alarm_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resource_backend", "请求资源后端错误"),
                    ("app_request", "蓝鲸应用请求错误"),
                    ("nginx_error", "Nginx错误"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="resource_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="资源 ID"),
        ),
        migrations.RunPython(fill_alarm_record_resource_id, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["app_code", "alarm_type", "id"],
                name="monitor_ar_app_type_id_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["app_code", "alarm_type", "resource_id", "id"],
                name="monitor_ar_app_type_res_id_idx",
            ),
        ),
    ]
