# Generated by Django 5.2.15 on 2026-07-03

import json

from django.db import migrations, models


def fill_alarm_record_fields(apps, schema_editor):
    AlarmRecord = apps.get_model("monitor", "AlarmRecord")

    records_to_update = []
    queryset = (
        AlarmRecord.objects.exclude(match_dimension="")
        .only("id", "match_dimension", "resource_id", "stage")
        .order_by("id")
    )

    for record in queryset.iterator(chunk_size=1000):
        try:
            match_dimension = json.loads(record.match_dimension)
        except (TypeError, ValueError):
            continue

        if not isinstance(match_dimension, dict):
            continue

        updated = False

        resource_id = match_dimension.get("resource_id")
        if isinstance(resource_id, str) and resource_id.isdigit():
            resource_id = int(resource_id)

        if record.resource_id is None and isinstance(resource_id, int):
            record.resource_id = resource_id
            updated = True

        stage = match_dimension.get("stage")
        if not record.stage and isinstance(stage, str):
            record.stage = stage
            updated = True

        if not updated:
            continue

        records_to_update.append(record)
        if len(records_to_update) >= 1000:
            AlarmRecord.objects.bulk_update(records_to_update, ["resource_id", "stage"])
            records_to_update = []

    if records_to_update:
        AlarmRecord.objects.bulk_update(records_to_update, ["resource_id", "stage"])


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0010_remove_alarmstrategy__api_label_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmrecord",
            name="app_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="alarm_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resource_backend", "请求资源后端错误"),
                    ("app_request", "蓝鲸应用请求错误"),
                    ("nginx_error", "Nginx错误"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="resource_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="资源 ID"),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.RunPython(fill_alarm_record_fields, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["app_code", "alarm_type", "created_time"],
                name="monitor_ar_app_type_time_idx",
            ),
        ),
    ]
