#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-03-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_auto_20200321_0938"),
    ]

    operations = [
        migrations.CreateModel(
            name="APISDK",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                ("filename", models.CharField(max_length=128)),
                ("language", models.CharField(choices=[("python", "PYTHON")], max_length=32)),
                ("version_number", models.CharField(max_length=64)),
                ("api", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.API")),
            ],
            options={
                "verbose_name": "网关SDK",
                "verbose_name_plural": "网关SDK",
                "db_table": "support_api_sdk",
            },
        ),
        migrations.CreateModel(
            name="ResourceDoc",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                ("type", models.CharField(choices=[("markdown", "MARKDOWN")], max_length=32)),
                ("content", models.TextField(blank=True, default="", null=True)),
                ("html_content", models.TextField(blank=True, default="", null=True)),
                ("resource", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="core.Resource")),
            ],
            options={
                "verbose_name": "资源文档",
                "verbose_name_plural": "资源文档",
                "db_table": "support_resource_doc",
            },
        ),
        migrations.AlterUniqueTogether(
            name="apisdk",
            unique_together={("api", "language", "version_number")},
        ),
    ]
