#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.2.11 on 2020-04-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schema", "0003_auto_20200401_2116"),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apisdk",
            name="_config",
            field=models.TextField(db_column="config", default="{}"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apisdk",
            name="include_private_resources",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apisdk",
            name="schema",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="schema.Schema"),
        ),
    ]
