#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-10-19 08:30

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20201009_1752"),
        ("support", "0008_apisdk_is_public_latest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleasedResourceDoc",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("resource_version_id", models.IntegerField(db_index=True)),
                ("resource_id", models.IntegerField(db_index=True)),
                ("data", jsonfield.fields.JSONField(help_text="resource doc data in resource doc version")),
                ("api", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.API")),
            ],
            options={
                "verbose_name": "ReleasedResourceDoc",
                "verbose_name_plural": "ReleasedResourceDoc",
                "db_table": "support_released_resource_doc",
            },
        ),
        migrations.AlterUniqueTogether(
            name="releasedresourcedoc",
            unique_together={("api", "resource_version_id", "resource_id")},
        ),
    ]
