#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0009_auto_20201019_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="apisdk",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="apisdk",
            name="is_recommended",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="apisdk",
            name="name",
            field=models.CharField(blank=True, default="", help_text="SDK 名称", max_length=128),
        ),
        migrations.AddField(
            model_name="apisdk",
            name="url",
            field=models.TextField(blank=True, default="", help_text="下载地址"),
        ),
        migrations.AlterField(
            model_name="apisdk",
            name="filename",
            field=models.CharField(help_text="SDK 文件名, 废弃", max_length=128),
        ),
        migrations.AlterField(
            model_name="apisdk",
            name="is_public_latest",
            field=models.BooleanField(db_index=True, default=False, help_text="废弃"),
        ),
        migrations.AlterField(
            model_name="apisdk",
            name="language",
            field=models.CharField(choices=[("unknown", "UNKNOWN"), ("python", "PYTHON")], max_length=32),
        ),
    ]
