#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-09-07 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0010_auto_20210825_2233"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceDocExtend",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("swagger", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "资源文档扩展",
                "verbose_name_plural": "资源文档扩展",
                "db_table": "support_resource_doc_extend",
            },
        ),
        migrations.RemoveField(
            model_name="resourcedoc",
            name="html_content",
        ),
        migrations.AddField(
            model_name="resourcedoc",
            name="language",
            field=models.CharField(choices=[("en", "英文"), ("zh", "中文")], db_index=True, default="zh", max_length=32),
        ),
        migrations.AddField(
            model_name="resourcedoc",
            name="source",
            field=models.CharField(
                choices=[("import-markdown", "导入 Markdown"), ("import-swagger", "导入 Swagger"), ("custom", "自定义")],
                db_index=True,
                default="custom",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="resourcedocextend",
            name="resource_doc",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="support.ResourceDoc"),
        ),
    ]
