# Generated by Django 3.2.18 on 2023-09-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_proxy_backend'),
        ('support', '0016_auto_20230818_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcedoc',
            old_name='api',
            new_name='gateway',
        ),
        migrations.RenameField(
            model_name='resourcedocswagger',
            old_name='api',
            new_name='gateway',
        ),
        migrations.AlterField(
            model_name='resourcedoc',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
        migrations.AlterField(
            model_name='resourcedoc',
            name='type',
            field=models.CharField(choices=[('markdown', 'Markdown')], max_length=32),
        ),
        migrations.AlterField(
            model_name='resourcedocswagger',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcedoc',
            unique_together={('gateway', 'resource_id', 'language')},
        ),
    ]
