# Generated by Django 4.2.20 on 2025-04-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0007_alter_schema_type'),
        ('core', '0044_gateway_kind'),
        ('support', '0017_auto_20230901_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcedocswagger',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='resourcedocswagger',
            name='resource_doc',
        ),
        migrations.DeleteModel(
            name='ResourceDocSwagger',
        ),
    ]
