# Generated by Django 5.2.15 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


def migrate_gateway_sdk_language_forward(apps, schema_editor):
    api_sdk = apps.get_model("support", "APISDK")
    api_sdk.objects.filter(language="golang").update(language="go")


def migrate_gateway_sdk_language_reverse(apps, schema_editor):
    api_sdk = apps.get_model("support", "APISDK")
    api_sdk.objects.filter(language="go").update(language="golang")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_rename_publishevent_gateway_publish_index"),
        ("support", "0018_remove_resourcedocswagger"),
    ]

    operations = [
        migrations.RunPython(migrate_gateway_sdk_language_forward, migrate_gateway_sdk_language_reverse),
        migrations.CreateModel(
            name="SDKGenerationTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        db_column="api_id", on_delete=django.db.models.deletion.CASCADE, to="core.gateway"
                    ),
                ),
                (
                    "resource_version",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.resourceversion"),
                ),
            ],
            options={"db_table": "support_sdk_generation_task"},
        ),
        migrations.CreateModel(
            name="SDKGenerationItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("python", "Python"),
                            ("java", "Java"),
                            ("go", "Go"),
                            ("javascript", "Javascript"),
                            ("rust", "Rust"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("lease_token", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("lease_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("input_fingerprint", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.CharField(blank=True, default="", max_length=1024)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="support.sdkgenerationtask",
                    ),
                ),
            ],
            options={"db_table": "support_sdk_generation_item"},
        ),
        migrations.CreateModel(
            name="SDKArtifact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                (
                    "distributor",
                    models.CharField(
                        choices=[("bkrepo_generic", "Bkrepo generic"), ("pypi", "Pypi"), ("maven", "Maven")],
                        default="bkrepo_generic",
                        max_length=32,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[("archive", "Archive"), ("package", "Package")], default="archive", max_length=32
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("remote_key", models.CharField(blank=True, default="", max_length=1024)),
                ("coordinate", models.CharField(blank=True, default="", max_length=512)),
                ("url", models.TextField(blank=True, default="")),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("original_version", models.CharField(blank=True, default="", max_length=64)),
                ("package_version", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="support.sdkgenerationitem",
                    ),
                ),
            ],
            options={"db_table": "support_sdk_artifact"},
        ),
        migrations.AddConstraint(
            model_name="sdkgenerationtask",
            constraint=models.UniqueConstraint(
                fields=("resource_version",), name="support_sdk_generation_task_resource_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkgenerationtask",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "running", "success", "partial", "failed"])),
                name="support_sdk_generation_task_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkgenerationitem",
            constraint=models.UniqueConstraint(
                fields=("task", "language"), name="support_sdk_generation_item_task_language_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkgenerationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__in", ("python", "java", "go", "javascript", "rust"))),
                name="support_sdk_generation_item_language_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkgenerationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "running", "success", "partial", "failed"])),
                name="support_sdk_generation_item_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkgenerationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 0)),
                name="support_sdk_generation_item_attempt_count_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkartifact",
            constraint=models.UniqueConstraint(
                fields=("item", "distributor", "filename"), name="support_sdk_artifact_item_distributor_filename_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("distributor__in", ["bkrepo_generic", "pypi", "maven"])),
                name="support_sdk_artifact_distributor_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("artifact_type__in", ["archive", "package"])),
                name="support_sdk_artifact_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "running", "success", "partial", "failed"])),
                name="support_sdk_artifact_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdkartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gte", 0)), name="support_sdk_artifact_size_valid"
            ),
        ),
    ]
