# Generated by Django 5.2.15 on 2026-09-03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0019_sdk_generation_tasks"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sdkgenerationtask",
            name="support_sdk_generation_task_resource_version_uniq",
        ),
    ]
