#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-06-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatisticsAPIRequestByDay",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("total_count", models.BigIntegerField(default=0)),
                ("failed_count", models.BigIntegerField(default=0)),
                ("total_msecs", models.BigIntegerField(default=0)),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                ("api_id", models.IntegerField(db_index=True)),
                ("stage_name", models.CharField(max_length=64)),
                ("resource_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "网关请求统计(按天)",
                "verbose_name_plural": "网关请求统计(按天)",
                "db_table": "metrics_stats_api_request_by_day",
            },
        ),
        migrations.CreateModel(
            name="StatisticsAppRequestByDay",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("total_count", models.BigIntegerField(default=0)),
                ("failed_count", models.BigIntegerField(default=0)),
                ("total_msecs", models.BigIntegerField(default=0)),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                ("api_id", models.IntegerField(db_index=True)),
                ("bk_app_code", models.CharField(max_length=32)),
                ("stage_name", models.CharField(max_length=64)),
                ("resource_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "应用请求统计(按天)",
                "verbose_name_plural": "应用请求统计(按天)",
                "db_table": "metrics_stats_app_request_by_day",
            },
        ),
    ]
