# Generated by Django 3.2.18 on 2023-06-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0005_auto_20230227_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginbinding',
            name='scope_type',
            field=models.CharField(choices=[('stage', '环境'), ('resource', '资源')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='description_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
