# Generated by Django 3.2.18 on 2023-08-15 02:05

from django.db import migrations
from django.db.models import Count


def forwards_func(apps, schema_editor):
    PluginConfig = apps.get_model("plugin", "PluginConfig")
    PluginBinding = apps.get_model("plugin", "PluginBinding")

    query = PluginBinding.objects.values("config_id").annotate(cnt=Count("config_id")).filter(cnt__gte=2)
    for d in query:
        config_id = d["config_id"]
        config = PluginConfig.objects.get(id=config_id)

        bindings = PluginBinding.objects.filter(config=config)
        count = 0
        for binding in bindings:
            count += 1
            if count == 1:
                # skip the first one, it keep the origin config
                continue

            # make a new config for the bind
            new_config = PluginConfig(
                gateway=config.gateway,
                name=config.name,
                type=config.type,
                description=config.description,
                description_en=config.description_en,
                yaml=config.yaml,
            )
            new_config.save()
            # update the binding's config
            binding.config = new_config
            binding.save()


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0007_auto_20230814_1526"),
    ]

    operations = [migrations.RunPython(forwards_func)]
