# Generated by Django 3.2.18 on 2023-08-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0008_auto_20230815_1005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="type",
            field=models.CharField(
                choices=[
                    ("ip-restriction", "IP访问控制"),
                    ("rate_limit", "频率控制"),
                    ("cors", "CORS"),
                    ("bk-verified-user-exempted-apps", "免用户认证应用白名单"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pluginbinding",
            name="type",
            field=models.CharField(
                choices=[
                    ("ip-restriction", "IP访问控制"),
                    ("rate_limit", "频率控制"),
                    ("cors", "CORS"),
                    ("bk-verified-user-exempted-apps", "免用户认证应用白名单"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pluginbinding",
            unique_together={("scope_id", "scope_type", "config")},
        ),
    ]
