# Generated by Django 3.2.18 on 2023-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0009_auto_20230815_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginbinding',
            name='scope_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pluginbinding',
            name='scope_type',
            field=models.CharField(choices=[('stage', '环境'), ('resource', '资源')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
