# Generated by Django 3.2.18 on 2023-08-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0010_auto_20230830_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugintype',
            name='scope',
            field=models.CharField(choices=[('stage', '环境'), ('resource', '资源'), ('stage_and_resource', '环境和资源')], default='stage_and_resource', max_length=32),
        ),
    ]
