# Generated by Django 3.2.25 on 2024-05-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0012_pluginbinding_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginbinding',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='pluginbinding',
            name='type',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
    ]
