# Generated by Django 4.2.23 on 2025-12-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0014_auto_20250321_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginbinding',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='pluginbinding',
            name='type',
        ),
        migrations.AddField(
            model_name='plugintype',
            name='_tags',
            field=models.CharField(blank=True, db_column='tags', default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pluginbinding',
            name='source',
            field=models.CharField(choices=[('yaml_import', 'yaml导入'), ('user_create', '用户创建'), ('user_update', '用户更新')], default='user_create', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
    ]
