# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0015_remove_pluginbinding_plugin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugintype",
            name="description",
            field=models.TextField(blank=True, default="", help_text="plugin type description"),
        ),
        migrations.AddField(
            model_name="plugintype",
            name="description_en",
            field=models.TextField(blank=True, default=None, null=True, help_text="plugin type description"),
        ),
    ]
