# Generated by Django 4.2.30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0016_add_plugintype_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PluginForm",
        ),
    ]
