# Generated by Django 4.2.20 on 2025-05-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0044_gateway_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "_labels",
                    models.CharField(
                        blank=True,
                        db_column="labels",
                        default="",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "_resource_ids",
                    models.CharField(
                        blank=True,
                        db_column="resource_ids",
                        default="",
                        max_length=1024,
                        null=True,
                    ),
                ),
                ("status", models.IntegerField(choices=[(0, "已停用"), (1, "启用中")])),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.gateway"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.stage"
                    ),
                ),
            ],
            options={
                "verbose_name": "MCPServer",
                "verbose_name_plural": "MCPServer",
                "db_table": "mcp_server",
            },
        ),
    ]
