# Generated by Django 4.2.20 on 2025-05-20 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpServerAppPermissionApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('bk_app_code', models.CharField(db_index=True, max_length=32)),
                ('applied_by', models.CharField(max_length=32)),
                ('applied_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('expire_days', models.IntegerField(default=0)),
                ('handled_by', models.CharField(blank=True, default='', max_length=32)),
                ('handled_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('pending', '待审批')], max_length=16)),
                ('mcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcp_server.mcpserver')),
            ],
            options={
                'verbose_name': 'MCPServer 应用申请审批',
                'verbose_name_plural': 'MCPServer 应用申请审批',
                'db_table': 'mcp_server_app_permission_apply',
                'indexes': [models.Index(fields=['mcp_server', 'status'], name='mcp_server__mcp_ser_8bcad0_idx')],
            },
        ),
        migrations.CreateModel(
            name='McpServerAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('bk_app_code', models.CharField(db_index=True, max_length=32)),
                ('expires', models.DateTimeField(blank=True, default=datetime.datetime(2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), help_text='默认过期时间为永久', null=True)),
                ('grant_type', models.CharField(choices=[('initialize', '主动授权'), ('apply', '申请审批')], db_index=True, max_length=16)),
                ('mcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcp_server.mcpserver')),
            ],
            options={
                'verbose_name': 'MCPServer 已授权应用',
                'verbose_name_plural': 'MCPServer 已授权应用',
                'db_table': 'mcp_server_app_permission',
                'unique_together': {('bk_app_code', 'mcp_server')},
            },
        ),
    ]
