# Generated by Django 4.2.20 on 2025-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp_server", "0002_auto_20250520_1471"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcpserver",
            name="_resource_names",
            field=models.TextField(
                blank=True, db_column="resource_names", default="", null=True
            ),
        ),
    ]
