# Generated by Django 4.2.23 on 2025-09-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0003_alter_mcpserver__resource_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserverapppermissionapply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
