# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0004_mcpserverapppermissionapply_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='title',
            field=models.CharField(blank=True, default='', help_text='MCPServer 中文名/显示名称', max_length=128),
        ),
    ]
