# Generated by Django 4.2.23 on 2025-12-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0005_mcpserver_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServerExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(choices=[('user_custom_doc', '用户自定义文档')], db_index=True, help_text='配置类型', max_length=32)),
                ('content', models.TextField(blank=True, default='', help_text='配置内容')),
                ('mcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extends', to='mcp_server.mcpserver')),
            ],
            options={
                'verbose_name': 'MCPServer 扩展配置',
                'verbose_name_plural': 'MCPServer 扩展配置',
                'db_table': 'mcp_server_extend',
                'unique_together': {('mcp_server', 'type')},
            },
        ),
    ]
