# Generated by Django 4.2.23 on 2025-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0006_mcpserverextend'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='protocol_type',
            field=models.CharField(choices=[('sse', 'SSE'), ('streamable_http', 'Streamable HTTP')], default='sse', help_text='MCP 协议类型', max_length=32),
        ),
    ]
