# Generated by Django 4.2.23 on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0006_mcpserverextend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserverextend',
            name='type',
            field=models.CharField(
                choices=[('user_custom_doc', '用户自定义文档'), ('prompts', 'Prompts 配置')],
                db_index=True,
                help_text='配置类型',
                max_length=32,
            ),
        ),
    ]
