# Generated by Django 4.2.23 on 2025-12-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0008_mcpserver_protocol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserver',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
