# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0011_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='oauth2_enabled',
            field=models.BooleanField(
                default=False,
                help_text='是否开启 OAuth2 认证，开启后自动为 bk_app_code=public 授权',
            ),
        ),
    ]
