# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0011_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='oauth2_public_client_enabled',
            field=models.BooleanField(
                default=False,
                help_text='是否开启 OAuth2 公开客户端模式，开启后将会对 bk_app_code=public 的应用进行授权',
            ),
        ),
    ]
