# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcp_server", "0012_mcpserver_oauth2_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mcpserver",
            old_name="oauth2_enabled",
            new_name="oauth2_public_client_enabled",
        ),
    ]
