# ====== test ======

.PHONY: test
test:
	cd .. && make test

.PHONY: test-pdb
test-pdb:
	cd .. && make test-pdb

# ====== edition ======

.PHONY: edition
edition:
	cd .. && make edition

.PHONY: edition-te
edition-te:
	cd .. && make edition-te

.PHONY: edition-ee
edition-ee:
	cd .. && make edition-ee

.PHONY: edition-reset
edition-reset:
	cd .. && make edition-reset
