# Generated by Django 3.2.18 on 2023-09-01 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_proxy_backend'),
        ('label', '0003_auto_20230227_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilabel',
            old_name='api',
            new_name='gateway',
        ),
        migrations.AlterField(
            model_name='apilabel',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
        migrations.AlterUniqueTogether(
            name='apilabel',
            unique_together={('gateway', 'name')},
        ),
    ]
