#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-03-05 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkcore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppPermissionApplyRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("board", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("bk_app_code", models.CharField(db_index=True, max_length=32)),
                ("applied_by", models.CharField(max_length=32)),
                ("applied_time", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, default="", max_length=512)),
                ("expire_days", models.IntegerField(default=180)),
                ("handled_by", models.CharField(blank=True, default="", max_length=32)),
                ("handled_time", models.DateTimeField(blank=True, null=True)),
                ("_component_ids", models.TextField(db_column="component_ids")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            ("partial_approved", "PARTIAL_APPROVED"),
                            ("approved", "APPROVED"),
                            ("rejected", "REJECTED"),
                            ("pending", "PENDING"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=512)),
                (
                    "system",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bkcore.ComponentSystem"),
                ),
            ],
            options={
                "verbose_name": "APP申请ESB组件权限单据",
                "verbose_name_plural": "APP申请ESB组件权限单据",
                "db_table": "esb_app_permission_apply_record",
            },
        ),
    ]
