#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-03-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkcore", "0003_auto_20210308_1431"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppPermissionApplyStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("board", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("bk_app_code", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("partial_approved", "部分通过"),
                            ("approved", "全部通过"),
                            ("rejected", "全部驳回"),
                            ("pending", "待审批"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "APP访问组件API权限申请状态",
                "verbose_name_plural": "APP访问组件API权限申请状态",
                "db_table": "esb_app_permission_apply_status",
            },
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否开启"),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="是否公开"),
        ),
        migrations.AddField(
            model_name="apppermissionapplystatus",
            name="component",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bkcore.ESBChannel"),
        ),
        migrations.AddField(
            model_name="apppermissionapplystatus",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bkcore.AppPermissionApplyRecord",
            ),
        ),
        migrations.AddField(
            model_name="apppermissionapplystatus",
            name="system",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bkcore.ComponentSystem"),
        ),
        migrations.AlterUniqueTogether(
            name="apppermissionapplystatus",
            unique_together={("board", "bk_app_code", "system", "component")},
        ),
    ]
