#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-04-25 08:02

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkcore", "0004_auto_20210308_1955"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppermissionapplyrecord",
            name="handled_component_ids",
            field=jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'indent': None}),
        ),
        migrations.AlterField(
            model_name="appcomponentpermission",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="apppermissionapplyrecord",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="apppermissionapplystatus",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="componentdoc",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="componentsystem",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="doccategory",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="config",
            field=jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'indent': None}),
        ),
        migrations.AlterField(
            model_name="esbchannelextend",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="functioncontroller",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="realtimelineevent",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
        migrations.AlterField(
            model_name="systemdoccategory",
            name="board",
            field=models.CharField(blank=True, db_index=True, default="default", max_length=64),
        ),
    ]
