#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-12-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkcore", "0008_auto_20211122_2044"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentResourceBinding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("board", models.CharField(blank=True, db_index=True, default="default", max_length=64)),
                ("component_id", models.IntegerField(default=0, verbose_name="组件 ID")),
                ("component_method", models.CharField(blank=True, default="", max_length=32, verbose_name="请求方法")),
                ("component_path", models.CharField(blank=True, default="", max_length=255, verbose_name="请求路径")),
                ("resource_id", models.IntegerField(unique=True, verbose_name="网关资源 ID")),
            ],
            options={
                "db_table": "esb_component_resource_binding",
            },
        ),
    ]
