#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2021-12-08 07:21

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkcore", "0009_componentresourcebinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentReleaseHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True)),
                ("board", models.CharField(blank=True, db_index=True, default="default", max_length=64)),
                ("resource_version_id", models.IntegerField(db_index=True, verbose_name="资源版本ID")),
                ("data", jsonfield.fields.JSONField(help_text="component sync data")),
                ("comment", models.CharField(blank=True, default="", max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "SUCCESS"), ("failure", "FAILURE"), ("pending", "PENDING")],
                        default="pending",
                        max_length=16,
                        verbose_name="发布状态",
                    ),
                ),
                ("message", models.TextField(blank=True, default="", verbose_name="发布消息")),
            ],
            options={
                "verbose_name": "组件同步网关及发布历史",
                "verbose_name_plural": "组件同步网关及发布历史",
                "db_table": "esb_component_release_history",
            },
        ),
    ]
