#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2022-09-23 03:56

from django.db import migrations, models

import apigateway.apps.permission.models


class Migration(migrations.Migration):

    dependencies = [
        ("bkcore", "0012_auto_20220516_1311"),
    ]

    operations = [
        migrations.AddField(
            model_name="esbchannel",
            name="verified_user_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="access_token",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="bk_app_code",
            field=models.CharField(max_length=128, verbose_name="蓝鲸应用编码"),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="expires",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="user_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="appaccount",
            name="app_code",
            field=models.CharField(max_length=30, unique=True, verbose_name="蓝鲸应用编码"),
        ),
        migrations.AlterField(
            model_name="appaccount",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="appaccount",
            name="introduction",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="appcomponentpermission",
            name="expires",
            field=models.DateTimeField(default=apigateway.apps.permission.models.generate_expire_time),
        ),
        migrations.AlterField(
            model_name="componentreleasehistory",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="componentresourcebinding",
            name="component_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="componentresourcebinding",
            name="component_method",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="componentresourcebinding",
            name="component_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="componentsystem",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="componentsystem",
            name="comment_en",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="componentsystem",
            name="description",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="componentsystem",
            name="description_en",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="componentsystem",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="componentsystem",
            name="timeout",
            field=models.IntegerField(blank=True, help_text="单位秒", null=True),
        ),
        migrations.AlterField(
            model_name="doccategory",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="doccategory",
            name="name_en",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="doccategory",
            name="priority",
            field=models.IntegerField(default=1000, help_text="数字大优先级高"),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="description",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="description_en",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="name",
            field=models.CharField(blank=True, default="", help_text="组件API英文名", max_length=128),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="permission_level",
            field=models.CharField(
                choices=[("unlimited", "无限制"), ("normal", "普通"), ("sensitive", "敏感"), ("special", "特殊")], max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="esbchannel",
            name="timeout",
            field=models.IntegerField(blank=True, help_text="单位秒", null=True),
        ),
        migrations.AlterField(
            model_name="realtimelineevent",
            name="system_name",
            field=models.CharField(max_length=32),
        ),
    ]
