# Generated by Django 3.2.18 on 2023-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkcore', '0013_auto_20220923_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermissionapplyrecord',
            name='gateway_apply_record_id',
            field=models.IntegerField(blank=True, help_text='网关 bk-esb 权限申请单ID，用于关联申请单，以获取网关申请单状态', null=True),
        ),
    ]