#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-09-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_strategy", "0004_auto_20200618_1231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessstrategy",
            name="type",
            field=models.CharField(
                choices=[
                    ("ip_access_control", "IP_ACCESS_CONTROL"),
                    ("rate_limit", "RATE_LIMIT"),
                    ("user_verified_unrequired_apps", "USER_VERIFIED_UNREQUIRED_APPS"),
                    ("error_status_code_200", "ERROR_STATUS_CODE_200"),
                    ("cors", "CORS"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="accessstrategybinding",
            name="type",
            field=models.CharField(
                choices=[
                    ("ip_access_control", "IP_ACCESS_CONTROL"),
                    ("rate_limit", "RATE_LIMIT"),
                    ("user_verified_unrequired_apps", "USER_VERIFIED_UNREQUIRED_APPS"),
                    ("error_status_code_200", "ERROR_STATUS_CODE_200"),
                    ("cors", "CORS"),
                ],
                max_length=32,
            ),
        ),
    ]
