#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-12-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_strategy", "0005_auto_20200927_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessstrategy",
            name="type",
            field=models.CharField(
                choices=[
                    ("ip_access_control", "IP访问控制"),
                    ("rate_limit", "频率控制"),
                    ("user_verified_unrequired_apps", "免用户认证应用白名单"),
                    ("error_status_code_200", "网关错误使用HTTP状态码200(不推荐)"),
                    ("cors", "跨域资源共享(CORS)"),
                    ("circuit_breaker", "断路器"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="accessstrategybinding",
            name="type",
            field=models.CharField(
                choices=[
                    ("ip_access_control", "IP访问控制"),
                    ("rate_limit", "频率控制"),
                    ("user_verified_unrequired_apps", "免用户认证应用白名单"),
                    ("error_status_code_200", "网关错误使用HTTP状态码200(不推荐)"),
                    ("cors", "跨域资源共享(CORS)"),
                    ("circuit_breaker", "断路器"),
                ],
                max_length=32,
            ),
        ),
    ]
