# Generated by Django 4.2.20 on 2025-05-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0044_gateway_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammableGatewayDeployHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('branch', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.CharField(db_index=True, default='', help_text='符合 semver 规范', max_length=128)),
                ('commit_id', models.CharField(blank=True, max_length=128, null=True)),
                ('deploy_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('source', models.CharField(choices=[('gateway_disable', '网关停用'), ('version_publish', '版本发布'), ('stage_disable', '环境下架')], default='version_publish', max_length=64)),
                ('publish_id', models.IntegerField(blank=True, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gateway')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stage')),
            ],
            options={
                'verbose_name': 'ProgrammableGatewayHistory',
                'verbose_name_plural': 'ProgrammableGatewayHistory',
                'db_table': 'programmable_gateway_deploy_history',
            },
        ),
    ]
