/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mcp_proxy/pkg/entity/model"
)

func newJWT(db *gorm.DB, opts ...gen.DOOption) jWT {
	_jWT := jWT{}

	_jWT.jWTDo.UseDB(db, opts...)
	_jWT.jWTDo.UseModel(&model.JWT{})

	tableName := _jWT.jWTDo.TableName()
	_jWT.ALL = field.NewAsterisk(tableName)
	_jWT.GatewayID = field.NewInt(tableName, "api_id")
	_jWT.PrivateKey = field.NewString(tableName, "private_key")
	_jWT.PublicKey = field.NewString(tableName, "public_key")
	_jWT.EncryptedPrivateKey = field.NewString(tableName, "encrypted_private_key")

	_jWT.fillFieldMap()

	return _jWT
}

type jWT struct {
	jWTDo jWTDo

	ALL                 field.Asterisk
	GatewayID           field.Int
	PrivateKey          field.String
	PublicKey           field.String
	EncryptedPrivateKey field.String

	fieldMap map[string]field.Expr
}

func (j jWT) Table(newTableName string) *jWT {
	j.jWTDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jWT) As(alias string) *jWT {
	j.jWTDo.DO = *(j.jWTDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jWT) updateTableName(table string) *jWT {
	j.ALL = field.NewAsterisk(table)
	j.GatewayID = field.NewInt(table, "api_id")
	j.PrivateKey = field.NewString(table, "private_key")
	j.PublicKey = field.NewString(table, "public_key")
	j.EncryptedPrivateKey = field.NewString(table, "encrypted_private_key")

	j.fillFieldMap()

	return j
}

func (j *jWT) WithContext(ctx context.Context) IJWTDo { return j.jWTDo.WithContext(ctx) }

func (j jWT) TableName() string { return j.jWTDo.TableName() }

func (j jWT) Alias() string { return j.jWTDo.Alias() }

func (j jWT) Columns(cols ...field.Expr) gen.Columns { return j.jWTDo.Columns(cols...) }

func (j *jWT) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jWT) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 4)
	j.fieldMap["api_id"] = j.GatewayID
	j.fieldMap["private_key"] = j.PrivateKey
	j.fieldMap["public_key"] = j.PublicKey
	j.fieldMap["encrypted_private_key"] = j.EncryptedPrivateKey
}

func (j jWT) clone(db *gorm.DB) jWT {
	j.jWTDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jWT) replaceDB(db *gorm.DB) jWT {
	j.jWTDo.ReplaceDB(db)
	return j
}

type jWTDo struct{ gen.DO }

type IJWTDo interface {
	gen.SubQuery
	Debug() IJWTDo
	WithContext(ctx context.Context) IJWTDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJWTDo
	WriteDB() IJWTDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJWTDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJWTDo
	Not(conds ...gen.Condition) IJWTDo
	Or(conds ...gen.Condition) IJWTDo
	Select(conds ...field.Expr) IJWTDo
	Where(conds ...gen.Condition) IJWTDo
	Order(conds ...field.Expr) IJWTDo
	Distinct(cols ...field.Expr) IJWTDo
	Omit(cols ...field.Expr) IJWTDo
	Join(table schema.Tabler, on ...field.Expr) IJWTDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJWTDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJWTDo
	Group(cols ...field.Expr) IJWTDo
	Having(conds ...gen.Condition) IJWTDo
	Limit(limit int) IJWTDo
	Offset(offset int) IJWTDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJWTDo
	Unscoped() IJWTDo
	Create(values ...*model.JWT) error
	CreateInBatches(values []*model.JWT, batchSize int) error
	Save(values ...*model.JWT) error
	First() (*model.JWT, error)
	Take() (*model.JWT, error)
	Last() (*model.JWT, error)
	Find() ([]*model.JWT, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JWT, err error)
	FindInBatches(result *[]*model.JWT, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JWT) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJWTDo
	Assign(attrs ...field.AssignExpr) IJWTDo
	Joins(fields ...field.RelationField) IJWTDo
	Preload(fields ...field.RelationField) IJWTDo
	FirstOrInit() (*model.JWT, error)
	FirstOrCreate() (*model.JWT, error)
	FindByPage(offset int, limit int) (result []*model.JWT, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJWTDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jWTDo) Debug() IJWTDo {
	return j.withDO(j.DO.Debug())
}

func (j jWTDo) WithContext(ctx context.Context) IJWTDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jWTDo) ReadDB() IJWTDo {
	return j.Clauses(dbresolver.Read)
}

func (j jWTDo) WriteDB() IJWTDo {
	return j.Clauses(dbresolver.Write)
}

func (j jWTDo) Session(config *gorm.Session) IJWTDo {
	return j.withDO(j.DO.Session(config))
}

func (j jWTDo) Clauses(conds ...clause.Expression) IJWTDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jWTDo) Returning(value interface{}, columns ...string) IJWTDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jWTDo) Not(conds ...gen.Condition) IJWTDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jWTDo) Or(conds ...gen.Condition) IJWTDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jWTDo) Select(conds ...field.Expr) IJWTDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jWTDo) Where(conds ...gen.Condition) IJWTDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jWTDo) Order(conds ...field.Expr) IJWTDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jWTDo) Distinct(cols ...field.Expr) IJWTDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jWTDo) Omit(cols ...field.Expr) IJWTDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jWTDo) Join(table schema.Tabler, on ...field.Expr) IJWTDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jWTDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJWTDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jWTDo) RightJoin(table schema.Tabler, on ...field.Expr) IJWTDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jWTDo) Group(cols ...field.Expr) IJWTDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jWTDo) Having(conds ...gen.Condition) IJWTDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jWTDo) Limit(limit int) IJWTDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jWTDo) Offset(offset int) IJWTDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jWTDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJWTDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jWTDo) Unscoped() IJWTDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jWTDo) Create(values ...*model.JWT) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jWTDo) CreateInBatches(values []*model.JWT, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jWTDo) Save(values ...*model.JWT) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jWTDo) First() (*model.JWT, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JWT), nil
	}
}

func (j jWTDo) Take() (*model.JWT, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JWT), nil
	}
}

func (j jWTDo) Last() (*model.JWT, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JWT), nil
	}
}

func (j jWTDo) Find() ([]*model.JWT, error) {
	result, err := j.DO.Find()
	return result.([]*model.JWT), err
}

func (j jWTDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JWT, err error) {
	buf := make([]*model.JWT, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jWTDo) FindInBatches(result *[]*model.JWT, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jWTDo) Attrs(attrs ...field.AssignExpr) IJWTDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jWTDo) Assign(attrs ...field.AssignExpr) IJWTDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jWTDo) Joins(fields ...field.RelationField) IJWTDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jWTDo) Preload(fields ...field.RelationField) IJWTDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jWTDo) FirstOrInit() (*model.JWT, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JWT), nil
	}
}

func (j jWTDo) FirstOrCreate() (*model.JWT, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JWT), nil
	}
}

func (j jWTDo) FindByPage(offset int, limit int) (result []*model.JWT, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jWTDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jWTDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jWTDo) Delete(models ...*model.JWT) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jWTDo) withDO(do gen.Dao) *jWTDo {
	j.DO = *do.(*gen.DO)
	return j
}
