/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mcp_proxy/pkg/entity/model"
)

func newReleasedResource(db *gorm.DB, opts ...gen.DOOption) releasedResource {
	_releasedResource := releasedResource{}

	_releasedResource.releasedResourceDo.UseDB(db, opts...)
	_releasedResource.releasedResourceDo.UseModel(&model.ReleasedResource{})

	tableName := _releasedResource.releasedResourceDo.TableName()
	_releasedResource.ALL = field.NewAsterisk(tableName)
	_releasedResource.ID = field.NewInt(tableName, "id")
	_releasedResource.ResourceVersionID = field.NewInt(tableName, "resource_version_id")
	_releasedResource.ResourceID = field.NewInt(tableName, "resource_id")
	_releasedResource.ResourceName = field.NewString(tableName, "resource_name")
	_releasedResource.ResourceMethod = field.NewString(tableName, "resource_method")
	_releasedResource.ResourcePath = field.NewString(tableName, "resource_path")
	_releasedResource.GatewayID = field.NewInt(tableName, "api_id")
	_releasedResource.Data = field.NewString(tableName, "data")

	_releasedResource.fillFieldMap()

	return _releasedResource
}

type releasedResource struct {
	releasedResourceDo releasedResourceDo

	ALL               field.Asterisk
	ID                field.Int
	ResourceVersionID field.Int
	ResourceID        field.Int
	ResourceName      field.String
	ResourceMethod    field.String
	ResourcePath      field.String
	GatewayID         field.Int
	Data              field.String

	fieldMap map[string]field.Expr
}

func (r releasedResource) Table(newTableName string) *releasedResource {
	r.releasedResourceDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r releasedResource) As(alias string) *releasedResource {
	r.releasedResourceDo.DO = *(r.releasedResourceDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *releasedResource) updateTableName(table string) *releasedResource {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt(table, "id")
	r.ResourceVersionID = field.NewInt(table, "resource_version_id")
	r.ResourceID = field.NewInt(table, "resource_id")
	r.ResourceName = field.NewString(table, "resource_name")
	r.ResourceMethod = field.NewString(table, "resource_method")
	r.ResourcePath = field.NewString(table, "resource_path")
	r.GatewayID = field.NewInt(table, "api_id")
	r.Data = field.NewString(table, "data")

	r.fillFieldMap()

	return r
}

func (r *releasedResource) WithContext(ctx context.Context) IReleasedResourceDo {
	return r.releasedResourceDo.WithContext(ctx)
}

func (r releasedResource) TableName() string { return r.releasedResourceDo.TableName() }

func (r releasedResource) Alias() string { return r.releasedResourceDo.Alias() }

func (r releasedResource) Columns(cols ...field.Expr) gen.Columns {
	return r.releasedResourceDo.Columns(cols...)
}

func (r *releasedResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *releasedResource) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["id"] = r.ID
	r.fieldMap["resource_version_id"] = r.ResourceVersionID
	r.fieldMap["resource_id"] = r.ResourceID
	r.fieldMap["resource_name"] = r.ResourceName
	r.fieldMap["resource_method"] = r.ResourceMethod
	r.fieldMap["resource_path"] = r.ResourcePath
	r.fieldMap["api_id"] = r.GatewayID
	r.fieldMap["data"] = r.Data
}

func (r releasedResource) clone(db *gorm.DB) releasedResource {
	r.releasedResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r releasedResource) replaceDB(db *gorm.DB) releasedResource {
	r.releasedResourceDo.ReplaceDB(db)
	return r
}

type releasedResourceDo struct{ gen.DO }

type IReleasedResourceDo interface {
	gen.SubQuery
	Debug() IReleasedResourceDo
	WithContext(ctx context.Context) IReleasedResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReleasedResourceDo
	WriteDB() IReleasedResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReleasedResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReleasedResourceDo
	Not(conds ...gen.Condition) IReleasedResourceDo
	Or(conds ...gen.Condition) IReleasedResourceDo
	Select(conds ...field.Expr) IReleasedResourceDo
	Where(conds ...gen.Condition) IReleasedResourceDo
	Order(conds ...field.Expr) IReleasedResourceDo
	Distinct(cols ...field.Expr) IReleasedResourceDo
	Omit(cols ...field.Expr) IReleasedResourceDo
	Join(table schema.Tabler, on ...field.Expr) IReleasedResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReleasedResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReleasedResourceDo
	Group(cols ...field.Expr) IReleasedResourceDo
	Having(conds ...gen.Condition) IReleasedResourceDo
	Limit(limit int) IReleasedResourceDo
	Offset(offset int) IReleasedResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReleasedResourceDo
	Unscoped() IReleasedResourceDo
	Create(values ...*model.ReleasedResource) error
	CreateInBatches(values []*model.ReleasedResource, batchSize int) error
	Save(values ...*model.ReleasedResource) error
	First() (*model.ReleasedResource, error)
	Take() (*model.ReleasedResource, error)
	Last() (*model.ReleasedResource, error)
	Find() ([]*model.ReleasedResource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReleasedResource, err error)
	FindInBatches(result *[]*model.ReleasedResource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ReleasedResource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReleasedResourceDo
	Assign(attrs ...field.AssignExpr) IReleasedResourceDo
	Joins(fields ...field.RelationField) IReleasedResourceDo
	Preload(fields ...field.RelationField) IReleasedResourceDo
	FirstOrInit() (*model.ReleasedResource, error)
	FirstOrCreate() (*model.ReleasedResource, error)
	FindByPage(offset int, limit int) (result []*model.ReleasedResource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReleasedResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r releasedResourceDo) Debug() IReleasedResourceDo {
	return r.withDO(r.DO.Debug())
}

func (r releasedResourceDo) WithContext(ctx context.Context) IReleasedResourceDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r releasedResourceDo) ReadDB() IReleasedResourceDo {
	return r.Clauses(dbresolver.Read)
}

func (r releasedResourceDo) WriteDB() IReleasedResourceDo {
	return r.Clauses(dbresolver.Write)
}

func (r releasedResourceDo) Session(config *gorm.Session) IReleasedResourceDo {
	return r.withDO(r.DO.Session(config))
}

func (r releasedResourceDo) Clauses(conds ...clause.Expression) IReleasedResourceDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r releasedResourceDo) Returning(value interface{}, columns ...string) IReleasedResourceDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r releasedResourceDo) Not(conds ...gen.Condition) IReleasedResourceDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r releasedResourceDo) Or(conds ...gen.Condition) IReleasedResourceDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r releasedResourceDo) Select(conds ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r releasedResourceDo) Where(conds ...gen.Condition) IReleasedResourceDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r releasedResourceDo) Order(conds ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r releasedResourceDo) Distinct(cols ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r releasedResourceDo) Omit(cols ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r releasedResourceDo) Join(table schema.Tabler, on ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r releasedResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r releasedResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r releasedResourceDo) Group(cols ...field.Expr) IReleasedResourceDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r releasedResourceDo) Having(conds ...gen.Condition) IReleasedResourceDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r releasedResourceDo) Limit(limit int) IReleasedResourceDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r releasedResourceDo) Offset(offset int) IReleasedResourceDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r releasedResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReleasedResourceDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r releasedResourceDo) Unscoped() IReleasedResourceDo {
	return r.withDO(r.DO.Unscoped())
}

func (r releasedResourceDo) Create(values ...*model.ReleasedResource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r releasedResourceDo) CreateInBatches(values []*model.ReleasedResource, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r releasedResourceDo) Save(values ...*model.ReleasedResource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r releasedResourceDo) First() (*model.ReleasedResource, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReleasedResource), nil
	}
}

func (r releasedResourceDo) Take() (*model.ReleasedResource, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReleasedResource), nil
	}
}

func (r releasedResourceDo) Last() (*model.ReleasedResource, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReleasedResource), nil
	}
}

func (r releasedResourceDo) Find() ([]*model.ReleasedResource, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReleasedResource), err
}

func (r releasedResourceDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.ReleasedResource, err error) {
	buf := make([]*model.ReleasedResource, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r releasedResourceDo) FindInBatches(
	result *[]*model.ReleasedResource,
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r releasedResourceDo) Attrs(attrs ...field.AssignExpr) IReleasedResourceDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r releasedResourceDo) Assign(attrs ...field.AssignExpr) IReleasedResourceDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r releasedResourceDo) Joins(fields ...field.RelationField) IReleasedResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r releasedResourceDo) Preload(fields ...field.RelationField) IReleasedResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r releasedResourceDo) FirstOrInit() (*model.ReleasedResource, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReleasedResource), nil
	}
}

func (r releasedResourceDo) FirstOrCreate() (*model.ReleasedResource, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReleasedResource), nil
	}
}

func (r releasedResourceDo) FindByPage(
	offset int,
	limit int,
) (result []*model.ReleasedResource, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r releasedResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r releasedResourceDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r releasedResourceDo) Delete(models ...*model.ReleasedResource) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *releasedResourceDo) withDO(do gen.Dao) *releasedResourceDo {
	r.DO = *do.(*gen.DO)
	return r
}
