/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
 * Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mcp_proxy/pkg/entity/model"
)

func newGateway(db *gorm.DB, opts ...gen.DOOption) gateway {
	_gateway := gateway{}

	_gateway.gatewayDo.UseDB(db, opts...)
	_gateway.gatewayDo.UseModel(&model.Gateway{})

	tableName := _gateway.gatewayDo.TableName()
	_gateway.ALL = field.NewAsterisk(tableName)
	_gateway.ID = field.NewInt(tableName, "id")
	_gateway.Name = field.NewString(tableName, "name")

	_gateway.fillFieldMap()

	return _gateway
}

type gateway struct {
	gatewayDo gatewayDo

	ALL  field.Asterisk
	ID   field.Int
	Name field.String

	fieldMap map[string]field.Expr
}

func (g gateway) Table(newTableName string) *gateway {
	g.gatewayDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gateway) As(alias string) *gateway {
	g.gatewayDo.DO = *(g.gatewayDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gateway) updateTableName(table string) *gateway {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt(table, "id")
	g.Name = field.NewString(table, "name")

	g.fillFieldMap()

	return g
}

func (g *gateway) WithContext(ctx context.Context) IGatewayDo { return g.gatewayDo.WithContext(ctx) }

func (g gateway) TableName() string { return g.gatewayDo.TableName() }

func (g gateway) Alias() string { return g.gatewayDo.Alias() }

func (g gateway) Columns(cols ...field.Expr) gen.Columns { return g.gatewayDo.Columns(cols...) }

func (g *gateway) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gateway) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 2)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
}

func (g gateway) clone(db *gorm.DB) gateway {
	g.gatewayDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gateway) replaceDB(db *gorm.DB) gateway {
	g.gatewayDo.ReplaceDB(db)
	return g
}

type gatewayDo struct{ gen.DO }

type IGatewayDo interface {
	gen.SubQuery
	Debug() IGatewayDo
	WithContext(ctx context.Context) IGatewayDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGatewayDo
	WriteDB() IGatewayDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGatewayDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGatewayDo
	Not(conds ...gen.Condition) IGatewayDo
	Or(conds ...gen.Condition) IGatewayDo
	Select(conds ...field.Expr) IGatewayDo
	Where(conds ...gen.Condition) IGatewayDo
	Order(conds ...field.Expr) IGatewayDo
	Distinct(cols ...field.Expr) IGatewayDo
	Omit(cols ...field.Expr) IGatewayDo
	Join(table schema.Tabler, on ...field.Expr) IGatewayDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGatewayDo
	Group(cols ...field.Expr) IGatewayDo
	Having(conds ...gen.Condition) IGatewayDo
	Limit(limit int) IGatewayDo
	Offset(offset int) IGatewayDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayDo
	Unscoped() IGatewayDo
	Create(values ...*model.Gateway) error
	CreateInBatches(values []*model.Gateway, batchSize int) error
	Save(values ...*model.Gateway) error
	First() (*model.Gateway, error)
	Take() (*model.Gateway, error)
	Last() (*model.Gateway, error)
	Find() ([]*model.Gateway, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Gateway, err error)
	FindInBatches(result *[]*model.Gateway, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Gateway) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGatewayDo
	Assign(attrs ...field.AssignExpr) IGatewayDo
	Joins(fields ...field.RelationField) IGatewayDo
	Preload(fields ...field.RelationField) IGatewayDo
	FirstOrInit() (*model.Gateway, error)
	FirstOrCreate() (*model.Gateway, error)
	FindByPage(offset int, limit int) (result []*model.Gateway, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGatewayDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gatewayDo) Debug() IGatewayDo {
	return g.withDO(g.DO.Debug())
}

func (g gatewayDo) WithContext(ctx context.Context) IGatewayDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gatewayDo) ReadDB() IGatewayDo {
	return g.Clauses(dbresolver.Read)
}

func (g gatewayDo) WriteDB() IGatewayDo {
	return g.Clauses(dbresolver.Write)
}

func (g gatewayDo) Session(config *gorm.Session) IGatewayDo {
	return g.withDO(g.DO.Session(config))
}

func (g gatewayDo) Clauses(conds ...clause.Expression) IGatewayDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gatewayDo) Returning(value interface{}, columns ...string) IGatewayDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gatewayDo) Not(conds ...gen.Condition) IGatewayDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gatewayDo) Or(conds ...gen.Condition) IGatewayDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gatewayDo) Select(conds ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gatewayDo) Where(conds ...gen.Condition) IGatewayDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gatewayDo) Order(conds ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gatewayDo) Distinct(cols ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gatewayDo) Omit(cols ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gatewayDo) Join(table schema.Tabler, on ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gatewayDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gatewayDo) RightJoin(table schema.Tabler, on ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gatewayDo) Group(cols ...field.Expr) IGatewayDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gatewayDo) Having(conds ...gen.Condition) IGatewayDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gatewayDo) Limit(limit int) IGatewayDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gatewayDo) Offset(offset int) IGatewayDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gatewayDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gatewayDo) Unscoped() IGatewayDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gatewayDo) Create(values ...*model.Gateway) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gatewayDo) CreateInBatches(values []*model.Gateway, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gatewayDo) Save(values ...*model.Gateway) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gatewayDo) First() (*model.Gateway, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gateway), nil
	}
}

func (g gatewayDo) Take() (*model.Gateway, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gateway), nil
	}
}

func (g gatewayDo) Last() (*model.Gateway, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gateway), nil
	}
}

func (g gatewayDo) Find() ([]*model.Gateway, error) {
	result, err := g.DO.Find()
	return result.([]*model.Gateway), err
}

func (g gatewayDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.Gateway, err error) {
	buf := make([]*model.Gateway, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gatewayDo) FindInBatches(result *[]*model.Gateway, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gatewayDo) Attrs(attrs ...field.AssignExpr) IGatewayDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gatewayDo) Assign(attrs ...field.AssignExpr) IGatewayDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gatewayDo) Joins(fields ...field.RelationField) IGatewayDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gatewayDo) Preload(fields ...field.RelationField) IGatewayDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gatewayDo) FirstOrInit() (*model.Gateway, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gateway), nil
	}
}

func (g gatewayDo) FirstOrCreate() (*model.Gateway, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gateway), nil
	}
}

func (g gatewayDo) FindByPage(offset int, limit int) (result []*model.Gateway, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gatewayDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gatewayDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gatewayDo) Delete(models ...*model.Gateway) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gatewayDo) withDO(do gen.Dao) *gatewayDo {
	g.DO = *do.(*gen.DO)
	return g
}
