/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                                 = new(Query)
	Gateway                           *gateway
	JWT                               *jWT
	MCPServer                         *mCPServer
	MCPServerAppPermission            *mCPServerAppPermission
	MCPServerExtend                   *mCPServerExtend
	OpenapiGatewayResourceVersionSpec *openapiGatewayResourceVersionSpec
	Release                           *release
	ReleasedResource                  *releasedResource
	Stage                             *stage
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Gateway = &Q.Gateway
	JWT = &Q.JWT
	MCPServer = &Q.MCPServer
	MCPServerAppPermission = &Q.MCPServerAppPermission
	MCPServerExtend = &Q.MCPServerExtend
	OpenapiGatewayResourceVersionSpec = &Q.OpenapiGatewayResourceVersionSpec
	Release = &Q.Release
	ReleasedResource = &Q.ReleasedResource
	Stage = &Q.Stage
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                                db,
		Gateway:                           newGateway(db, opts...),
		JWT:                               newJWT(db, opts...),
		MCPServer:                         newMCPServer(db, opts...),
		MCPServerAppPermission:            newMCPServerAppPermission(db, opts...),
		MCPServerExtend:                   newMCPServerExtend(db, opts...),
		OpenapiGatewayResourceVersionSpec: newOpenapiGatewayResourceVersionSpec(db, opts...),
		Release:                           newRelease(db, opts...),
		ReleasedResource:                  newReleasedResource(db, opts...),
		Stage:                             newStage(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Gateway                           gateway
	JWT                               jWT
	MCPServer                         mCPServer
	MCPServerAppPermission            mCPServerAppPermission
	MCPServerExtend                   mCPServerExtend
	OpenapiGatewayResourceVersionSpec openapiGatewayResourceVersionSpec
	Release                           release
	ReleasedResource                  releasedResource
	Stage                             stage
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                                db,
		Gateway:                           q.Gateway.clone(db),
		JWT:                               q.JWT.clone(db),
		MCPServer:                         q.MCPServer.clone(db),
		MCPServerAppPermission:            q.MCPServerAppPermission.clone(db),
		MCPServerExtend:                   q.MCPServerExtend.clone(db),
		OpenapiGatewayResourceVersionSpec: q.OpenapiGatewayResourceVersionSpec.clone(db),
		Release:                           q.Release.clone(db),
		ReleasedResource:                  q.ReleasedResource.clone(db),
		Stage:                             q.Stage.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                                db,
		Gateway:                           q.Gateway.replaceDB(db),
		JWT:                               q.JWT.replaceDB(db),
		MCPServer:                         q.MCPServer.replaceDB(db),
		MCPServerAppPermission:            q.MCPServerAppPermission.replaceDB(db),
		MCPServerExtend:                   q.MCPServerExtend.replaceDB(db),
		OpenapiGatewayResourceVersionSpec: q.OpenapiGatewayResourceVersionSpec.replaceDB(db),
		Release:                           q.Release.replaceDB(db),
		ReleasedResource:                  q.ReleasedResource.replaceDB(db),
		Stage:                             q.Stage.replaceDB(db),
	}
}

type queryCtx struct {
	Gateway                           IGatewayDo
	JWT                               IJWTDo
	MCPServer                         IMCPServerDo
	MCPServerAppPermission            IMCPServerAppPermissionDo
	MCPServerExtend                   IMCPServerExtendDo
	OpenapiGatewayResourceVersionSpec IOpenapiGatewayResourceVersionSpecDo
	Release                           IReleaseDo
	ReleasedResource                  IReleasedResourceDo
	Stage                             IStageDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Gateway:                           q.Gateway.WithContext(ctx),
		JWT:                               q.JWT.WithContext(ctx),
		MCPServer:                         q.MCPServer.WithContext(ctx),
		MCPServerAppPermission:            q.MCPServerAppPermission.WithContext(ctx),
		MCPServerExtend:                   q.MCPServerExtend.WithContext(ctx),
		OpenapiGatewayResourceVersionSpec: q.OpenapiGatewayResourceVersionSpec.WithContext(ctx),
		Release:                           q.Release.WithContext(ctx),
		ReleasedResource:                  q.ReleasedResource.WithContext(ctx),
		Stage:                             q.Stage.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
