/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mcp_proxy/pkg/entity/model"
)

func newMCPServerAppPermission(db *gorm.DB, opts ...gen.DOOption) mCPServerAppPermission {
	_mCPServerAppPermission := mCPServerAppPermission{}

	_mCPServerAppPermission.mCPServerAppPermissionDo.UseDB(db, opts...)
	_mCPServerAppPermission.mCPServerAppPermissionDo.UseModel(&model.MCPServerAppPermission{})

	tableName := _mCPServerAppPermission.mCPServerAppPermissionDo.TableName()
	_mCPServerAppPermission.ALL = field.NewAsterisk(tableName)
	_mCPServerAppPermission.Id = field.NewInt(tableName, "id")
	_mCPServerAppPermission.BkAppCode = field.NewString(tableName, "bk_app_code")
	_mCPServerAppPermission.Expires = field.NewTime(tableName, "expires")
	_mCPServerAppPermission.GrantType = field.NewString(tableName, "grant_type")
	_mCPServerAppPermission.McpServerId = field.NewInt(tableName, "mcp_server_id")

	_mCPServerAppPermission.fillFieldMap()

	return _mCPServerAppPermission
}

type mCPServerAppPermission struct {
	mCPServerAppPermissionDo mCPServerAppPermissionDo

	ALL         field.Asterisk
	Id          field.Int
	BkAppCode   field.String
	Expires     field.Time
	GrantType   field.String
	McpServerId field.Int

	fieldMap map[string]field.Expr
}

func (m mCPServerAppPermission) Table(newTableName string) *mCPServerAppPermission {
	m.mCPServerAppPermissionDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mCPServerAppPermission) As(alias string) *mCPServerAppPermission {
	m.mCPServerAppPermissionDo.DO = *(m.mCPServerAppPermissionDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mCPServerAppPermission) updateTableName(table string) *mCPServerAppPermission {
	m.ALL = field.NewAsterisk(table)
	m.Id = field.NewInt(table, "id")
	m.BkAppCode = field.NewString(table, "bk_app_code")
	m.Expires = field.NewTime(table, "expires")
	m.GrantType = field.NewString(table, "grant_type")
	m.McpServerId = field.NewInt(table, "mcp_server_id")

	m.fillFieldMap()

	return m
}

func (m *mCPServerAppPermission) WithContext(ctx context.Context) IMCPServerAppPermissionDo {
	return m.mCPServerAppPermissionDo.WithContext(ctx)
}

func (m mCPServerAppPermission) TableName() string { return m.mCPServerAppPermissionDo.TableName() }

func (m mCPServerAppPermission) Alias() string { return m.mCPServerAppPermissionDo.Alias() }

func (m mCPServerAppPermission) Columns(cols ...field.Expr) gen.Columns {
	return m.mCPServerAppPermissionDo.Columns(cols...)
}

func (m *mCPServerAppPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mCPServerAppPermission) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.Id
	m.fieldMap["bk_app_code"] = m.BkAppCode
	m.fieldMap["expires"] = m.Expires
	m.fieldMap["grant_type"] = m.GrantType
	m.fieldMap["mcp_server_id"] = m.McpServerId
}

func (m mCPServerAppPermission) clone(db *gorm.DB) mCPServerAppPermission {
	m.mCPServerAppPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mCPServerAppPermission) replaceDB(db *gorm.DB) mCPServerAppPermission {
	m.mCPServerAppPermissionDo.ReplaceDB(db)
	return m
}

type mCPServerAppPermissionDo struct{ gen.DO }

type IMCPServerAppPermissionDo interface {
	gen.SubQuery
	Debug() IMCPServerAppPermissionDo
	WithContext(ctx context.Context) IMCPServerAppPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMCPServerAppPermissionDo
	WriteDB() IMCPServerAppPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMCPServerAppPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMCPServerAppPermissionDo
	Not(conds ...gen.Condition) IMCPServerAppPermissionDo
	Or(conds ...gen.Condition) IMCPServerAppPermissionDo
	Select(conds ...field.Expr) IMCPServerAppPermissionDo
	Where(conds ...gen.Condition) IMCPServerAppPermissionDo
	Order(conds ...field.Expr) IMCPServerAppPermissionDo
	Distinct(cols ...field.Expr) IMCPServerAppPermissionDo
	Omit(cols ...field.Expr) IMCPServerAppPermissionDo
	Join(table schema.Tabler, on ...field.Expr) IMCPServerAppPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMCPServerAppPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMCPServerAppPermissionDo
	Group(cols ...field.Expr) IMCPServerAppPermissionDo
	Having(conds ...gen.Condition) IMCPServerAppPermissionDo
	Limit(limit int) IMCPServerAppPermissionDo
	Offset(offset int) IMCPServerAppPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMCPServerAppPermissionDo
	Unscoped() IMCPServerAppPermissionDo
	Create(values ...*model.MCPServerAppPermission) error
	CreateInBatches(values []*model.MCPServerAppPermission, batchSize int) error
	Save(values ...*model.MCPServerAppPermission) error
	First() (*model.MCPServerAppPermission, error)
	Take() (*model.MCPServerAppPermission, error)
	Last() (*model.MCPServerAppPermission, error)
	Find() ([]*model.MCPServerAppPermission, error)
	FindInBatch(
		batchSize int,
		fc func(tx gen.Dao, batch int) error,
	) (results []*model.MCPServerAppPermission, err error)
	FindInBatches(result *[]*model.MCPServerAppPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MCPServerAppPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMCPServerAppPermissionDo
	Assign(attrs ...field.AssignExpr) IMCPServerAppPermissionDo
	Joins(fields ...field.RelationField) IMCPServerAppPermissionDo
	Preload(fields ...field.RelationField) IMCPServerAppPermissionDo
	FirstOrInit() (*model.MCPServerAppPermission, error)
	FirstOrCreate() (*model.MCPServerAppPermission, error)
	FindByPage(offset int, limit int) (result []*model.MCPServerAppPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMCPServerAppPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mCPServerAppPermissionDo) Debug() IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Debug())
}

func (m mCPServerAppPermissionDo) WithContext(ctx context.Context) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mCPServerAppPermissionDo) ReadDB() IMCPServerAppPermissionDo {
	return m.Clauses(dbresolver.Read)
}

func (m mCPServerAppPermissionDo) WriteDB() IMCPServerAppPermissionDo {
	return m.Clauses(dbresolver.Write)
}

func (m mCPServerAppPermissionDo) Session(config *gorm.Session) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Session(config))
}

func (m mCPServerAppPermissionDo) Clauses(conds ...clause.Expression) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mCPServerAppPermissionDo) Returning(value interface{}, columns ...string) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mCPServerAppPermissionDo) Not(conds ...gen.Condition) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mCPServerAppPermissionDo) Or(conds ...gen.Condition) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mCPServerAppPermissionDo) Select(conds ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mCPServerAppPermissionDo) Where(conds ...gen.Condition) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mCPServerAppPermissionDo) Order(conds ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mCPServerAppPermissionDo) Distinct(cols ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mCPServerAppPermissionDo) Omit(cols ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mCPServerAppPermissionDo) Join(table schema.Tabler, on ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mCPServerAppPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mCPServerAppPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mCPServerAppPermissionDo) Group(cols ...field.Expr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mCPServerAppPermissionDo) Having(conds ...gen.Condition) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mCPServerAppPermissionDo) Limit(limit int) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mCPServerAppPermissionDo) Offset(offset int) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mCPServerAppPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mCPServerAppPermissionDo) Unscoped() IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mCPServerAppPermissionDo) Create(values ...*model.MCPServerAppPermission) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mCPServerAppPermissionDo) CreateInBatches(values []*model.MCPServerAppPermission, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mCPServerAppPermissionDo) Save(values ...*model.MCPServerAppPermission) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mCPServerAppPermissionDo) First() (*model.MCPServerAppPermission, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServerAppPermission), nil
	}
}

func (m mCPServerAppPermissionDo) Take() (*model.MCPServerAppPermission, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServerAppPermission), nil
	}
}

func (m mCPServerAppPermissionDo) Last() (*model.MCPServerAppPermission, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServerAppPermission), nil
	}
}

func (m mCPServerAppPermissionDo) Find() ([]*model.MCPServerAppPermission, error) {
	result, err := m.DO.Find()
	return result.([]*model.MCPServerAppPermission), err
}

func (m mCPServerAppPermissionDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.MCPServerAppPermission, err error) {
	buf := make([]*model.MCPServerAppPermission, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mCPServerAppPermissionDo) FindInBatches(
	result *[]*model.MCPServerAppPermission,
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mCPServerAppPermissionDo) Attrs(attrs ...field.AssignExpr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mCPServerAppPermissionDo) Assign(attrs ...field.AssignExpr) IMCPServerAppPermissionDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mCPServerAppPermissionDo) Joins(fields ...field.RelationField) IMCPServerAppPermissionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mCPServerAppPermissionDo) Preload(fields ...field.RelationField) IMCPServerAppPermissionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mCPServerAppPermissionDo) FirstOrInit() (*model.MCPServerAppPermission, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServerAppPermission), nil
	}
}

func (m mCPServerAppPermissionDo) FirstOrCreate() (*model.MCPServerAppPermission, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServerAppPermission), nil
	}
}

func (m mCPServerAppPermissionDo) FindByPage(
	offset int,
	limit int,
) (result []*model.MCPServerAppPermission, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mCPServerAppPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mCPServerAppPermissionDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mCPServerAppPermissionDo) Delete(models ...*model.MCPServerAppPermission) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mCPServerAppPermissionDo) withDO(do gen.Dao) *mCPServerAppPermissionDo {
	m.DO = *do.(*gen.DO)
	return m
}
