/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mcp_proxy/pkg/entity/model"
)

func newMCPServer(db *gorm.DB, opts ...gen.DOOption) mCPServer {
	_mCPServer := mCPServer{}

	_mCPServer.mCPServerDo.UseDB(db, opts...)
	_mCPServer.mCPServerDo.UseModel(&model.MCPServer{})

	tableName := _mCPServer.mCPServerDo.TableName()
	_mCPServer.ALL = field.NewAsterisk(tableName)
	_mCPServer.ID = field.NewInt(tableName, "id")
	_mCPServer.Name = field.NewString(tableName, "name")
	_mCPServer.Description = field.NewString(tableName, "description")
	_mCPServer.IsPublic = field.NewBool(tableName, "is_public")
	_mCPServer.Labels = field.NewField(tableName, "labels")
	_mCPServer.ResourceNames = field.NewField(tableName, "resource_names")
	_mCPServer.Status = field.NewInt(tableName, "status")
	_mCPServer.GatewayID = field.NewInt(tableName, "gateway_id")
	_mCPServer.StageID = field.NewInt(tableName, "stage_id")

	_mCPServer.fillFieldMap()

	return _mCPServer
}

type mCPServer struct {
	mCPServerDo mCPServerDo

	ALL           field.Asterisk
	ID            field.Int
	Name          field.String
	Description   field.String
	IsPublic      field.Bool
	Labels        field.Field
	ResourceNames field.Field
	Status        field.Int
	GatewayID     field.Int
	StageID       field.Int

	fieldMap map[string]field.Expr
}

func (m mCPServer) Table(newTableName string) *mCPServer {
	m.mCPServerDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mCPServer) As(alias string) *mCPServer {
	m.mCPServerDo.DO = *(m.mCPServerDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mCPServer) updateTableName(table string) *mCPServer {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt(table, "id")
	m.Name = field.NewString(table, "name")
	m.Description = field.NewString(table, "description")
	m.IsPublic = field.NewBool(table, "is_public")
	m.Labels = field.NewField(table, "labels")
	m.ResourceNames = field.NewField(table, "resource_names")
	m.Status = field.NewInt(table, "status")
	m.GatewayID = field.NewInt(table, "gateway_id")
	m.StageID = field.NewInt(table, "stage_id")

	m.fillFieldMap()

	return m
}

func (m *mCPServer) WithContext(ctx context.Context) IMCPServerDo {
	return m.mCPServerDo.WithContext(ctx)
}

func (m mCPServer) TableName() string { return m.mCPServerDo.TableName() }

func (m mCPServer) Alias() string { return m.mCPServerDo.Alias() }

func (m mCPServer) Columns(cols ...field.Expr) gen.Columns { return m.mCPServerDo.Columns(cols...) }

func (m *mCPServer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mCPServer) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["description"] = m.Description
	m.fieldMap["is_public"] = m.IsPublic
	m.fieldMap["labels"] = m.Labels
	m.fieldMap["resource_names"] = m.ResourceNames
	m.fieldMap["status"] = m.Status
	m.fieldMap["gateway_id"] = m.GatewayID
	m.fieldMap["stage_id"] = m.StageID
}

func (m mCPServer) clone(db *gorm.DB) mCPServer {
	m.mCPServerDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mCPServer) replaceDB(db *gorm.DB) mCPServer {
	m.mCPServerDo.ReplaceDB(db)
	return m
}

type mCPServerDo struct{ gen.DO }

type IMCPServerDo interface {
	gen.SubQuery
	Debug() IMCPServerDo
	WithContext(ctx context.Context) IMCPServerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMCPServerDo
	WriteDB() IMCPServerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMCPServerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMCPServerDo
	Not(conds ...gen.Condition) IMCPServerDo
	Or(conds ...gen.Condition) IMCPServerDo
	Select(conds ...field.Expr) IMCPServerDo
	Where(conds ...gen.Condition) IMCPServerDo
	Order(conds ...field.Expr) IMCPServerDo
	Distinct(cols ...field.Expr) IMCPServerDo
	Omit(cols ...field.Expr) IMCPServerDo
	Join(table schema.Tabler, on ...field.Expr) IMCPServerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMCPServerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMCPServerDo
	Group(cols ...field.Expr) IMCPServerDo
	Having(conds ...gen.Condition) IMCPServerDo
	Limit(limit int) IMCPServerDo
	Offset(offset int) IMCPServerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMCPServerDo
	Unscoped() IMCPServerDo
	Create(values ...*model.MCPServer) error
	CreateInBatches(values []*model.MCPServer, batchSize int) error
	Save(values ...*model.MCPServer) error
	First() (*model.MCPServer, error)
	Take() (*model.MCPServer, error)
	Last() (*model.MCPServer, error)
	Find() ([]*model.MCPServer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MCPServer, err error)
	FindInBatches(result *[]*model.MCPServer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MCPServer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMCPServerDo
	Assign(attrs ...field.AssignExpr) IMCPServerDo
	Joins(fields ...field.RelationField) IMCPServerDo
	Preload(fields ...field.RelationField) IMCPServerDo
	FirstOrInit() (*model.MCPServer, error)
	FirstOrCreate() (*model.MCPServer, error)
	FindByPage(offset int, limit int) (result []*model.MCPServer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMCPServerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mCPServerDo) Debug() IMCPServerDo {
	return m.withDO(m.DO.Debug())
}

func (m mCPServerDo) WithContext(ctx context.Context) IMCPServerDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mCPServerDo) ReadDB() IMCPServerDo {
	return m.Clauses(dbresolver.Read)
}

func (m mCPServerDo) WriteDB() IMCPServerDo {
	return m.Clauses(dbresolver.Write)
}

func (m mCPServerDo) Session(config *gorm.Session) IMCPServerDo {
	return m.withDO(m.DO.Session(config))
}

func (m mCPServerDo) Clauses(conds ...clause.Expression) IMCPServerDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mCPServerDo) Returning(value interface{}, columns ...string) IMCPServerDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mCPServerDo) Not(conds ...gen.Condition) IMCPServerDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mCPServerDo) Or(conds ...gen.Condition) IMCPServerDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mCPServerDo) Select(conds ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mCPServerDo) Where(conds ...gen.Condition) IMCPServerDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mCPServerDo) Order(conds ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mCPServerDo) Distinct(cols ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mCPServerDo) Omit(cols ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mCPServerDo) Join(table schema.Tabler, on ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mCPServerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mCPServerDo) RightJoin(table schema.Tabler, on ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mCPServerDo) Group(cols ...field.Expr) IMCPServerDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mCPServerDo) Having(conds ...gen.Condition) IMCPServerDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mCPServerDo) Limit(limit int) IMCPServerDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mCPServerDo) Offset(offset int) IMCPServerDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mCPServerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMCPServerDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mCPServerDo) Unscoped() IMCPServerDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mCPServerDo) Create(values ...*model.MCPServer) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mCPServerDo) CreateInBatches(values []*model.MCPServer, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mCPServerDo) Save(values ...*model.MCPServer) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mCPServerDo) First() (*model.MCPServer, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServer), nil
	}
}

func (m mCPServerDo) Take() (*model.MCPServer, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServer), nil
	}
}

func (m mCPServerDo) Last() (*model.MCPServer, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServer), nil
	}
}

func (m mCPServerDo) Find() ([]*model.MCPServer, error) {
	result, err := m.DO.Find()
	return result.([]*model.MCPServer), err
}

func (m mCPServerDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.MCPServer, err error) {
	buf := make([]*model.MCPServer, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mCPServerDo) FindInBatches(
	result *[]*model.MCPServer,
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mCPServerDo) Attrs(attrs ...field.AssignExpr) IMCPServerDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mCPServerDo) Assign(attrs ...field.AssignExpr) IMCPServerDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mCPServerDo) Joins(fields ...field.RelationField) IMCPServerDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mCPServerDo) Preload(fields ...field.RelationField) IMCPServerDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mCPServerDo) FirstOrInit() (*model.MCPServer, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServer), nil
	}
}

func (m mCPServerDo) FirstOrCreate() (*model.MCPServer, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MCPServer), nil
	}
}

func (m mCPServerDo) FindByPage(offset int, limit int) (result []*model.MCPServer, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mCPServerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mCPServerDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mCPServerDo) Delete(models ...*model.MCPServer) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mCPServerDo) withDO(do gen.Dao) *mCPServerDo {
	m.DO = *do.(*gen.DO)
	return m
}
