#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 2.0.13 on 2020-12-22 03:24

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                (
                    'doc_type',
                    models.CharField(
                        choices=[('platform', 'PLATFORM'), ('component', 'COMPONENT'), ('apigateway', 'APIGATEWAY')],
                        max_length=32,
                        verbose_name='文档类型',
                    ),
                ),
                ('labels', jsonfield.fields.JSONField(default=list, verbose_name='问题类型')),
                ('link', models.CharField(blank=True, default='', max_length=1024, verbose_name='文档链接')),
                ('content', models.TextField(blank=True, default='', verbose_name='反馈内容')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='', verbose_name='截图')),
            ],
            options={
                'verbose_name': '文档反馈',
                'verbose_name_plural': '文档反馈',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='FeedbackRelatedAPIGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
            ],
            options={
                'verbose_name': '文档反馈-关联网关',
                'verbose_name_plural': '文档反馈-关联网关',
                'db_table': 'feedback_related_apigateway',
            },
        ),
        migrations.CreateModel(
            name='FeedbackRelatedComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('system_name', models.CharField(max_length=32, verbose_name='组件系统')),
                ('component_name', models.CharField(blank=True, default='', max_length=64, verbose_name='组件名称')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
            ],
            options={
                'verbose_name': '文档反馈-关联组件',
                'verbose_name_plural': '文档反馈-关联组件',
                'db_table': 'feedback_related_component',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers', models.CharField(max_length=1024, verbose_name='接收人')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('received', 'RECEIVED'),
                            ('skipped', 'SKIPPED'),
                            ('success', 'SUCCESS'),
                            ('failure', 'FAILURE'),
                        ],
                        max_length=32,
                        verbose_name='通知状态',
                    ),
                ),
                ('message', models.TextField(blank=True, default='', verbose_name='通知结果')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
            ],
            options={
                'verbose_name': '文档反馈通知',
                'verbose_name_plural': '文档反馈通知',
                'db_table': 'feedback_notice',
            },
        ),
    ]
