# -*- coding: utf-8 -*-
#
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - API 网关(BlueKing - APIGateway) available.
# Copyright (C) 2025 Tencent. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.
#
# Generated by Django 4.2 on 2026-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItsmSystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="修改时间")),
                ("system_code", models.CharField(help_text="系统标识", max_length=64, unique=True)),
                ("system_name", models.CharField(help_text="系统名称", max_length=256)),
                ("system_desc", models.CharField(blank=True, default="", help_text="系统描述", max_length=1024)),
                ("itsm_system_id", models.CharField(blank=True, default="", help_text="ITSM 系统 ID", max_length=64)),
                ("system_token", models.CharField(blank=True, default="", help_text="系统调用 Token", max_length=256)),
                ("workflow_key", models.CharField(blank=True, default="", help_text="ITSM 流程标识", max_length=64)),
                ("workflow_name", models.CharField(blank=True, default="", help_text="流程名称", max_length=256)),
                ("workflow_category", models.CharField(blank=True, default="", help_text="流程分类", max_length=64)),
                ("portal_id", models.CharField(blank=True, default="DEFAULT", help_text="门户 ID", max_length=64)),
                ("is_registered", models.BooleanField(default=False, help_text="是否已完成系统+流程注册")),
            ],
            options={
                "verbose_name": "ITSM 系统配置",
                "verbose_name_plural": "ITSM 系统配置",
                "db_table": "bk_itsm_system_config",
            },
        ),
    ]
