# Generated by Django 3.2.25 on 2024-04-25 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0040_alter_publishevent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAPIResourceSchemaVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('schema', models.JSONField(blank=True, null=True)),
                ('resource_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.resourceversion')),
            ],
            options={
                'db_table': 'openapi_resource_schema_version',
            },
        ),
        migrations.CreateModel(
            name='OpenAPIResourceSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('schema', models.JSONField(blank=True, null=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
            ],
            options={
                'db_table': 'openapi_resource_schema',
            },
        ),
    ]
