# Generated by Django 4.2.16 on 2025-05-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_gateway_kind'),
        ('openapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAPIFileResourceSchemaVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('schema', models.TextField(blank=True, null=True)),
                ('gateway', models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.PROTECT, to='core.gateway')),
                ('resource_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.resourceversion')),
            ],
            options={
                'db_table': 'openapi_file_resource_schema_version',
            },
        ),
    ]
