# Generated by Django 4.2.23 on 2026-01-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0002_openapifileresourceschemaversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openapifileresourceschemaversion',
            name='gateway',
            field=models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, to='core.gateway'),
        ),
        migrations.AlterField(
            model_name='openapifileresourceschemaversion',
            name='resource_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.resourceversion'),
        ),
        migrations.AlterField(
            model_name='openapiresourceschemaversion',
            name='resource_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.resourceversion'),
        ),
    ]
