# Generated by Django 5.2.15 on 2026-08-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0056_releasedresource_oauth2_scope_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('administrator', '管理员'), ('operator', '运营者')], max_length=32)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(db_column='api_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.gateway')),
            ],
            options={
                'db_table': 'core_gateway_member',
                'unique_together': {('gateway', 'username')},
            },
        ),
    ]
